### ISSUE TITLE
Add Lil' scrubber

### ISSUE THREAD

**Issue by adamjarling** [samvera-labs/ramp#12]
### Description

Add lil' scrub to the iiif-player like we have in the avalon player

The code that makes this work could possibly be pulled from the Avalon Media System player itself...

![Screenshot from 2020-03-02 11-02-46.png](https://images.zenhubusercontent.com/5cc1c66b3244e00362de97ea/c416de08-f05a-434f-b000-fb91265ecd4e)

Related to #5216. Note that we want to retain the functionality of the detailed scrub, but the design in the UI can be updated.

### Done Looks Like

iiif-player has a lil' scrubber

**Comment by joncameron** [comment]
Broader discussion about whether the particular UI for lil' scrub needs to be retained should happen, in the content of more options/flexibility being available in this player.

**Comment by elynema** [comment]
Keep current functionality, but could be re-imagined in the UI. Jon would like to brainstorm some options and propose a basic mockup for review.

**Comment by joncameron** [comment]
See #227
