### ISSUE TITLE
Add IIIF media player to IIIF viewer matrix

### ISSUE THREAD

**Issue by elynema** [samvera-labs/ramp#146]
Depends upon #145.

Raise awareness of IIIF media player in IIIF community by adding it to the [IIIF viewer matrix](https://iiif.io/api/cookbook/recipe/matrix/).

# Done
- [x] Update code to include IIIF viewer (https://github.com/IIIF/cookbook-recipes)
- [x] Add our IIIF Player to the list in the AV recipe descriptions (currently UV and Mirador are listed)

**Comment by Dananji** [comment]
I added React IIIF media player to IIIF viewer matrix, and it looks like follows in the matrix and in individual recipe page respectively;

![iiif_matrix.png](https://images.zenhubusercontent.com/5cc1c66b3244e00362de97ea/0a36a17d-5d14-4430-aee0-50e587e0f3bf)

![cookbook_recipe.png](https://images.zenhubusercontent.com/5cc1c66b3244e00362de97ea/0042c085-18b2-47b0-a991-880038e99e27)

I haven't pushed these changes to the cookbook repository yet. I think it's better if we can change the name of the component before we publish this.

**Comment by joncameron** [comment]
The IIIF community interoperability spreadsheet should also be updated once this is completed.

**Comment by elynema** [comment]
Dananji will attend the next cookbook team meeting to get this PR approved.

**Comment by elynema** [comment]
pull request has been submitted to cookbook and reviewed with them and just waiting on their approval.
