### ISSUE TITLE
Add to Playlist Component

### ISSUE THREAD

**Issue by joncameron** [samvera-labs/ramp#163]
# Description
On Avalon media object show pages, users can take action to add sections or ranges of sections to playlists. This can be created as a component in Ramp.

![image.png](https://images.zenhubusercontent.com/62d989a70c79cb5218735cd6/b561ce0a-1d52-4937-841f-e054d7d0010f)

# Done Looks Like
- [x] Determine whether the functionality to add an ad hoc timed clip (rather than an existing section or segment) to a playlist needs to be retained (it does)
- [ ] Add to playlist button is available, even if there is only one section (currently section details do not display in Avalon if only one section)

**Comment by elynema** [comment]
I believe it is an open question whether this functionality will be retained? There is also an add to playlist icon on each section of the object. It does not allow clipping to add a segment of a file to a playlist. We were going to consult with the MCO working group on whether that use case is still needed.

@joncameron Is this straightforward enough of a question that you could email the MCO working group rather than waiting for the next meeting?

**Comment by elynema** [comment]
Emailed MCO working group on use case for time-based clips being added to playlists on 5/22.

**Comment by elynema** [comment]
Could the time-based clip add to playlist button be placed underneath the video player next to Create Thumbnail button? Check out Matt's designs to see if this looks reasonable.

**Comment by joncameron** [comment]
Retain "Add New Playlist" on the Playlist selection drop-down/typeahead field. We can re-use the existing one used in the current "Add to Playlist" form when the button is clicked within the media player.

**Comment by joncameron** [comment]
Our "Add New Playlist" doesn't populate a newly created playlist on the page without a refresh. It should!

**Comment by joncameron** [comment]
![IMG_1375.jpg](https://images.zenhubusercontent.com/5cc1c0106d0be2229caf2d9e/a3c7b8c6-c760-49d5-b45f-3c06be3b434e)

**Comment by elynema** [comment]
@joncameron This issue was created as a Ramp issue, but it sounds like the code is actually going to live in Avalon for first iteration. If we can't move this issue to a different repository, we may need to re-create it in the avalon repository?

**Comment by joncameron** [comment]
Close this and open a new issue in the avalon repository to implement the above design for the media object page rework.
