### ISSUE TITLE
Add, edit, delete markers in playlists

### ISSUE THREAD

**Issue by elynema** [samvera-labs/ramp#167]
# Description

When playing an item from a playlist, there is an "add marker" component in the player. This allows the user to create a named marker at a specific timepoint in the playlist item.

![image.png](https://images.zenhubusercontent.com/62d989a70c79cb5218735cd6/5804fb0c-7d31-4ff3-a747-d8611a9f8427)

It seems like this could be modeled in IIIF pretty easily and potentially handled by Ramp, but need to discuss. Initially, we proposed moving this outside of Ramp and implementing with Avalon.

Priority: must have (must retain marker functionality in playlists somehow)

# Done looks like

- [ ] "add marker" button in Ramp media player only renders when the marker annotation service is referenced for the playlist item
- [ ] Edit / Delete marker buttons only show up in the list of markers if the marker annotation service is referenced for the playlist item
- [ ] After clicking "add marker" in media player, user can create a title for the marker. The offset automatically populates with the current offset, but can be edited by the user.
- [x] After clicking "edit" for an existing marker, the user can edit the title or offset for the marker and save.
- [x] After clicking "delete" for an existing marker, there is a confirmation popup to ensure the user wants to delete the marker.

**Comment by elynema** [comment]
To be discussed in Swarm on 6/21.

Potential options:

- somehow pull this functionality out of the player and implement in Avalon code
- implement this functionality generically as a component in Ramp using an Avalon service that is declared in the manifest?
- is there a way to implement directly in Ramp? IIIF has a list of tools, a number of which enable the creation of annotations. One example is Adno (see Github code).
-

**Comment by elynema** [comment]
Plug in an annotation service so that Ramp can talk utilize the service to create, update, and display markers. Need to have authorization, as we have playlists where anyone can see markers but only the owner can create/update.

Use https://github.com/PenguinParadigm/annotot as an example of a simple annotation server. Because we need to build in authorization, we will roll over own annotation server within Avalon by creating the API endpoints needed by Ramp.

**Comment by elynema** [comment]
Add markers was wired up at co-working Friday, so mostly just CSS remaining. Dananji can work on  that.

**Comment by masaball** [comment]
At the end of our swarm time on Friday we ran into a bug with the delete functionality. When a user deletes a marker, the last item in the marker list is what gets removed from the marker display regardless of which marker the user tried to delete.

We need to verify if the correct marker is being deleted on the Avalon side and the display is being updated incorrectly or if the wrong marker is being deleted, and fix the functionality.

**Comment by Dananji** [comment]
Things still needs fixing:
- Switching between items when add new marker form is open is giving an error
- Switching between playlist items after adding a new marker/deleting an existing marker doesn't reflect the newly added/deleted marker in the table
 To reproduce:
  - add/delete a marker in a playlist item 
  - updates the markers table accordingly 
  - navigate to a different item
  - come back to the first playlist item the marker changes were done 
  - doesn't reflect the changes to the markers in the table

**Comment by elynema** [comment]
Ramp reloads markers from central storage where manifest is parsed at initial load, so new markers were not retained in Ramp. Updated the create / update / delete to update central storage as well as back-end.

**Comment by elynema** [comment]
This has been merged into Ramp and is in the build that Avalon is using. Once this component is added to the playlist page, it can be tested.

**Comment by joncameron** [comment]
Tested successfully in samvera-labs/ramp/#298; closing this long-running issue as markers are now functional!
