### ISSUE TITLE
Create supplemental file component for Ramp

### ISSUE THREAD

**Issue by elynema** [samvera-labs/ramp#173]
# Description

Ramp already displays supplementing annotations as transcripts and captions. Add a component to display rendering properties that may contain supplemental files.

Note that Ramp already offers download of files within the player for files available via the rendering property (which can be enabled / disabled). However, we'd like to add a component that makes these files available outside of the player and added on the page where desired.

![image.png](https://images.zenhubusercontent.com/62d989a70c79cb5218735cd6/aca19228-ba7c-418c-ab3c-ecb097179161)

# Questions
- [x] Do we want to change the labeling of item/section files at all? Should this be configurable for other users who want to use different labeling terminology? Should section files be also labeled with some kind of title from the section itself?
- [x] What should we do with waveform files? Not display them?
 - use seeAlso property to hold information about the waveform data (seeAlso not currently used) so that it doesn't appear with supplemental files for end users
 - iiif-manifest gem doesn't currently have the ability to add seeAlso values
- [x] Should we distinguish which files to display based on type or format?
- No, display all rendering property files. Something outside of the basic IIIF types (audio, video, text) gets put assigned "Dataset"
- We want to avoid Avalon-specific logic in Ramp

# Definition of Done
- [x] New component created under Ramp - "SupplementalFiles" (or a different name as appropriate)
- [x] The component should display both files available at the manifest level (called Item files in Avalon) and files available at the canvas level (called Section files in Avalon). These 2 types of files should be distinguished with a header.
- [x] All files available via the rendering property are listed for download (listed as rendering properties)
- [x] Captions and transcripts are supplementing annotations, but should also be included for download
- [x] Heading text should be configurable by users (i.e. passed as props, no references to "Item" and "Section" if not desired by external users)
- [x] File names should be able to contain UTF-8 characters

**Comment by Dananji** [comment]
Wiki documentation for the component: https://github.com/samvera-labs/ramp/wiki/SupplementalFiles-Component
