### ISSUE TITLE
Indicate machine-generated transcripts in transcript component in Ramp

### ISSUE THREAD

**Issue by elynema** [samvera-labs/ramp#175]
# Description
Transcripts which are marked as machine-generated will have a message to the user indicating this status in the transcript component.

See UI mockup in #5054 investigation ticket.

This ticket also covers the work to distinguish captions and transcripts separately for display for the specific Avalon implementation of #5172 (see PR #5226). Since we only have the `supplementing` annotation to work with at this time, we decided to use the URI in Avalon manifests to identify transcripts vs. captions (ex: `/master_files/:master_file_id/supplememtal_files/:id/captions`). In order to work for this avalon-specific customization, Ramp needs to be able to parse these URI patterns. Otherwise, all `supplementing` annotations will be displayed as both transcript and caption.

# Definition of Done

- [ ] For transcripts where the machine-generated checkbox is checked in Avalon and is noted in the IIIF manifest for a transcript, text "Machine-generated transcript may contain errors" should display just below the transcript selection drop-down box on the media object page. This text should not scroll with transcript.
- [ ] Transcript downloads contain text in the filename indicating the machine-generated origin of the transcript
  - [ ] the string "(machine generated)" is contained in the filename, at the end of the name before the extension, as in "Oral History Transcript (machine generated).vtt" to the filename
 - [ ] Transcripts in Avalon manifests (as specified in URI) are displayed only as transcripts (not as caption options)
 - [ ] Captions in Avalon manifests (as specified in URI) are displayed only as captions (not as transcripts)
 - [ ] All other supplementing annotations (not marked as transcripts or captions) are displayed as both a transcript and a caption
 
# Screenshot Goes Here!

**Comment by Dananji** [comment]
For machine generated transcripts, provided the manifest supplies the necessary information (a value of a property within the annotation to indicate the transcript is machine generated) to identify a transcript as machine generated, Transcript component can add ` (machine generated)` text to the filename when downloading.
