### ISSUE TITLE
Add Previous and Next Buttons to navigate between Canvases

### ISSUE THREAD

**Issue by joncameron** [samvera-labs/ramp#176]
# Description
When there are multiple canvases in a manifest, Ramp should allow for navigation between them via controls on the player's toolbar. With back and next buttons available when there is more than one file, users can navigate more quickly. VideoJS appears to have an icon for this under "previous-item".

# Definition of Done
- [ ] When more than one canvas/file is present in a manifest, "back" and "next" buttons appear next to the Play button
- [ ] Selecting the back button will load the preceding canvas media into the player
- [ ] Selecting the next button will load the following canvas media into the player
- [ ] Selecting Back on the first section will restart the section from the beginning
- [ ] Selecting Next on the last section will have no effect

# Mockup
![Screenshot 2023-05-17 at 2.50.56 PM.jpg](https://images.zenhubusercontent.com/5cc1c0106d0be2229caf2d9e/28b252c7-5239-42fc-a883-0851bcd58f8f)

**Comment by elynema** [comment]
Used video.js to create custom components to previous and next buttons. If only a single canvas, just the play button. If more than one canvas, instantiate the previous and next buttons.

On first canvas, hover over previous button says "Replay". On second or later canvas, hover over previous button says "Next"
