### ISSUE TITLE
Adjust color contrast for links and text highlighting

### ISSUE THREAD

**Issue by joncameron** [samvera-labs/ramp#181]
# Description
Changing the default link color for Ramp's structure component. Right now there isn't enough contrast in the default styling with gray text on white background and that fails AA and AAA guidelines. Proposing to make the default #2A5459 instead, from Avalon's branding palette:
![Screenshot 2023-08-16 at 2 27 57 PM](https://github.com/samvera-labs/ramp/assets/1406618/f81b48cd-0866-4aae-a501-2a83f0f6c19a)

# Done Looks Like
- [x] Links in structured nav component are #2A5459

# Current
![Screenshot 2023-08-16 at 2 29 34 PM](https://github.com/samvera-labs/ramp/assets/1406618/5d01029d-66d3-45ae-82b7-21f974609397)

# New Look
![Screenshot 2023-08-16 at 2 29 52 PM](https://github.com/samvera-labs/ramp/assets/1406618/0d1daad2-a27f-4ce4-bdb2-50d143542097)

**Comment by Dananji** [comment]
Adjust color contrast for structured navigation links when hovered over when using a mouse pointer.
