### ISSUE TITLE
Adjust CSS and player toolbar for page zoom and resize

### ISSUE THREAD

**Issue by joncameron** [samvera-labs/ramp#182]
# Description
Video.js has a resize component that can be investigated. Right now, at 200% the player toolbar has elements that slide out of view. This is a possible accessibility issue.

# Currently (200% zoom)
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBdVVOIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--d7cbd2854204a39815451c0dd6440e3e1616410f/Screenshot%202023-08-16%20at%202.53.02%20PM.png)

# Done Looks Like
- [ ] All UI elements are shown in the media player when a browser is set to 200% zoom

**Comment by joncameron** [comment]
This will likely involve CSS for Video.js.

**Comment by Dananji** [comment]
Testing note:
For different zoom levels in the browser (e.g.: 50%, 100%, 200%, 250%) test the player for both audio and video.
Things to look for:
- hover over the quality selector/closed captions/file download icons works
- the menus for quality selection/closed captions/file download are properly displayed (font-size)
- captions are properly displayed (font-size)
- time tooltip is displayed when hovering over the timerail (progressbar) and can seek to a timestamp
- big play button in the center of the video player is displayed

**Comment by charumitraravi** [comment]
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMlFNQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--a44fe179dcd1c3cf688da13f5782ed4fb334affe/Screenshot%202023-10-05%20at%201.28.55%20PM.png)
The play button appears to be slightly left aligned

**Comment by elynema** [comment]
@Dananji Charu noted some alignment of the big play button in the center of the player at high zoo levels. Is that an easy fix? If it's not, then we can close and move on.

**Comment by Dananji** [comment]
This was an easy fix. I have a PR: https://github.com/samvera-labs/ramp/pull/262

**Comment by elynema** [comment]
Need to re-test centering of play button.

**Comment by charumitraravi** [comment]
Retested. The issue seems to be resolved now
@elynema @Dananji
