### ISSUE TITLE
Adjust playback speed of the player

### ISSUE THREAD

**Issue by joncameron** [samvera-labs/ramp#185]
Video.js includes a component to adjust playback speed; could we use that and add an option to Ramp to add this to the player when present in the configuration. Documentation may be an issue but it should be straightforward.

# Done Looks Like
- [x] Should be available as prop
- [x] Add option for speed control to our VideoJS configuration
- [x] Evaluate functionality and look and feel

**Comment by Dananji** [comment]
This implementation introduces a prop to the `MediaPlayer` component called `enablePlaybackRate` which adds `PlaybackRateMenuButton` to the player's control bar. This provides the ability to adjust the playback speed of the media. 

The provided speeds are: 0.5x, 0.75x, 1x, 1.5x, and 2x.

#### Testing Note

To adjust the playback speed:
- click the button icon (shows up as 1x on initial load), and on consecutive clicks the the speed goes from 1x -> 1.5x -> 2x -> 0.5x -> 0.75x -> back to 1x
- select the desired playback speed from the menu that appears with playback speeds when hovered over using a mouse pointer
- keyboard accessibility - once navigated to the button using `TAB` key, pressing either `ENTER` or `SPACEBAR` key changes the speed in the same order as clicking on the icon

**Comment by elynema** [comment]
Adding this button takes up more space in the menu; starting to run out of space, especially on small screens. Might want to consider a broader 'settings' button? Potentially look at Youtube. So this is a first pass implementation.

**Comment by Dananji** [comment]
This can be tested on Ramp demo site.

**Comment by elynema** [comment]
The playback speed widget is appearing and working now that it is turned on in Avalon. Note that on mobile devices, there is no hover menu; it just toggles speeds when you click on it. There seems to be some spacing issues on some mobile devices; I will create a new issue for that.
