### ISSUE TITLE
Stop auto-advancing from canvas to canvas within the player

### ISSUE THREAD

**Issue by joncameron** [samvera-labs/ramp#186]
# Description

IIIF manifest spec has "no auto-advance" as the default behavior; auto-advance is the default behavior of Avalon. The auto-advance functionality in Ramp as implemented can be used to retain our current Avalon functionality.

- toggle to enable/disable auto-advance (implemented in Ramp, not working right now due to a bug). We can choose to display the toggle or not for user interaction.
- implement user notifications for when changes happen within the player (like moving from section to section)
  - what aria/event notifications need to occur? 

Other sites
- Youtube (how does auto-play work here?)

# Done Looks Like
- [x] Investigate other streaming sites
- [x] Research on what is required to notify user about changes to media player
- [x] Create new tickets to modify Avalon/Ramp behavior as needed

**Comment by Dananji** [comment]
From an accessibility perspective:

Re-reding the WCAG guidelines for the particular accessibility issue that pointed out the autoplay feature;

> If any audio on a Web page plays automatically for more than 3 seconds, either a mechanism is available to pause or stop the audio, or a mechanism is available to control audio volume independently from the overall system volume level. (Level A)

Ramp has the ability to pause playback when autoplay happens. Therefore Ramp partially conforms to this. As we are in the initial stage of accessibility fixes I feel like this is good.
If this is acceptable to the team, then Ramp doesn't require to implement anything new or change the current functionality around auto-advance with regards to accessibility.

Solutions other popular streaming sites use for autoplay:
- YouTube: it has autoplay turned on by default. When a video ends, it gives the option to cancel/continue to next video with a 10 second timer.
- Vimeo: has autoplay turned on. Gives a preview of what's next on the side with a 10 second timer without jumping to the next video instantly when playback ends.

We could adapt a similar solution in Ramp in the future as a next step.

From a IIIF perspective:
The default temporal behavior in a IIIF Manifest is to, `no-auto-advance` (Reference: https://iiif.io/api/presentation/3.0/#behavior)
Therefore default behavior of Ramp to auto-advance to the next available Canvas when playback ends is not the accepted behavior. The default behavior when playback reaches the end of a Canvas is to reset the player and stop playback. This needs to be fixed. Related issue:

**Comment by joncameron** [comment]
@joncameron to test again—demo site should reflect current dev status of Ramp

**Comment by elynema** [comment]
Ramp no longer auto-advances by default. However, playlists and media objects in Avalon will auto-advance by default.

Agree with Dananji that the WCAG language "A mechanism is available to pause/stop automatically played audio" is met by the ability to stop/start playback with keyboard. Ramp #236 is an improvement for accessibility, but probably not required.
