### ISSUE TITLE
Change volume adjuster

### ISSUE THREAD

**Issue by joncameron** [samvera-labs/ramp#189]
# Description
Currently opens up horizontally; we've discussed changing this default behavior. The desire is to have a vertical adjustment more like we have in Avalon now for video items. The current horizontal UI is confusing as it gets tangled up in the progress bar area when it expands. Instead, Avalon's existing placement of the volume button and slider can be recreated within Ramp.

A vertical volume adjuster can be set up when videojs is instantiated. Audio only items need to be tested—removing the animation may need some work, but it will still need to be horizontal to be functional in an embedded view, or when the height of the player div is very low (as in the current Avalon video player).

# Done Looks Like
- [x]  Volume Button moved to the right side of the progress bar, to the left of the settings button (cog icon)
- [x]  Volume slider is always present on audio items (no animation to reveal)
- [x]  Video slider only displays on mouseover for video items
- [x]  Video slider is vertical for video items

# Current Avalon
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBckdZIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--595ab32fdefadd847ebaa9c904414ba5fbb0771c/Screenshot%202023-09-13%20at%202.58.15%20PM.png)

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBcktZIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--16a1878aded6759e01b18ad974adc3ef196c16d9/Screenshot%202023-09-13%20at%202.58.21%20PM.png)

# Current Ramp/Video.js
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBck9ZIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--01d4952fcdd34ae7b565908e2aec3dcd113b6102/Screenshot%202023-09-13%20at%202.46.54%20PM.png)

**Comment by Dananji** [comment]
Testing note:
- Volume panel can be accessed via keyboard for both audio and video players

**Comment by elynema** [comment]
Need to test keyboard navigation with new audio bar in Chrome and Safari.
