### ISSUE TITLE
Add styling to Ramp Structure Component

### ISSUE THREAD

**Issue by elynema** [samvera-labs/ramp#191]
# Description

Implement styling for structured navigation from the new media object page design (#5202). See new mockup: https://mco.stagingcenter.com/

Note: originally attempted to implement accordion-style expand / collapse for sections, but that proved challenging, so moved that to Ramp #247 to investigate further.

# Done Looks Like
- [ ] duration shows for sections and timespans 
- [ ] sections are numbered
- [ ] section titles have larger font than timespans / headings than structure within a section
- [ ] all sections display, even when there is no structure for that section
- [ ] sections scroll (without scrolling the full page) when there are more sections than can display on the page
- [ ] horizontal lines between each section

**Comment by elynema** [comment]
Making sure expand/collapse buttons in section display have text alternatives from screen readers is one issue identified by SiteImprove.

**Comment by elynema** [comment]
This has not been merged to avalon-dev; need to test in Ramp demo site.

**Comment by charumitraravi** [comment]
Performed QA on the Ramp demo site. UI looks fine. Found 2 issues:
1. Unable to select and play the sections which do not have timespans (Danajni mentioned its a known issue tagged under - [259](https://app.zenhub.com/workspaces/avalon-5bff96674b5806bc2bf90276/issues/gh/samvera-labs/ramp/259)
 [Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOXdsQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--7b94d1ab534d7bd3fd2e754c6f8f4b62050573f4/Screenshot%202023-10-11%20at%209.44.36%20AM.png)
2. When I scroll up in the page while the player is playing, the page automatically scrolls down. Is it expected?

**Comment by elynema** [comment]
Not yet merged into dev; do we want to QA again once it's in dev?

**Comment by elynema** [comment]
@charumitraravi This is now available on avalon-dev, so check out that scrolling error again!

**Comment by charumitraravi** [comment]
Issue is happening in Avalon dev as well. Added a bug for the same. - [5422](https://app.zenhub.com/workspaces/avalon-5bff96674b5806bc2bf90276/issues/gh/avalonmediasystem/avalon/5422)

@elynema @Dananji

**Comment by elynema** [comment]
@charumitraravi Would you mind doing a quick QA on this now that is is merged into avalon-dev? Or let us know if you've already done this? I believe we have issues created for the other items you found.

**Comment by charumitraravi** [comment]
@elynema Performed qa on this item on avalon dev.  There were no new issues.

**Comment by elynema** [comment]
@charumitraravi Did you test the "collapse [x] sections" button in the screen reader to see if it has a text alternative?
