### ISSUE TITLE
Ramp should adhere to start and end times for Playlist items

### ISSUE THREAD

**Issue by masaball** [samvera-labs/ramp#205]
**Describe the bug**
Playlist items can be created as clips, with a specific start and end time. The new IIIF playlist manifest implementation handles this by having each playlist item represented as a canvas, with the clip duration as a top level range. 

Selecting a playlist item will cause the media to start from the proper start time but the media will continue playing past the end time. If a user lets the media autoplay or uses the next/previous buttons to navigate, the media ignores the range completely and plays from beginning to end.

**To Reproduce**
1. Go to the Ramp demo site
2. Paste a url for a playlist manifest containing clipped media objects into the Manifest URL bar
3. Click "Set Manifest"
4. Play the first item to the end so the autoplay moves to the next item
5. _Item will start playing from beginning, rather than the start of the range_
6. Click on the previous button
7. _Item will start playing from beginning, rather than the start of the range_
8. Click on another playlist item and let it play
9. _Item will start playing from the start time, but will not stop playing at the end time_

**Expected behavior**
Playlist items only play for the range defined in the manifest.

**Screenrecording**
[Example](https://images.zenhubusercontent.com/310684521/4fdc4406-69c2-4dc0-94ee-eb996a603ea8/playlist_autoplay_2023_07_12_11_32_17.mp4)

**Desktop (please complete the following information):**
 - OS: Ubuntu 22.04
 - Browser: Firefox
 - Version: 114.0.1
 - 

# Questions
- Is there a selector for time ranges within IIIF that we should be using?
- Where in the manifest will time fragment be to indicate that only a certain range of a media file should be displayed?

# Done Looks Like
- [x] Investigation and decision on representing time fragments for playlist items in IIIF (see notes and questions)
- [ ] Playlist manifests contain time range information for playlist items at the Canvas level via time fragments, rather than within ranges
- [ ] Duration for painting canvas matches duration of time fragment

# Examples
- https://iiif.io/api/cookbook/recipe/0015-start/ (point selector; is there a range selector?)
- https://iiif.io/api/cookbook/recipe/0064-opera-one-canvas/
- https://iiif.io/api/cookbook/recipe/0065-opera-multiple-canvases/

**Comment by joncameron** [comment]
Alternative: using Canvas ranges, rather than structure ranges. Range on Canvas will on render that time in the timeline within the player.

**Comment by joncameron** [comment]
Instead of time fragments on item IDs, each painting annotation has a target which usually has the Canvas ID, but could contain time fragments.

**Comment by joncameron** [comment]
Topic for swarm 7/19.

**Comment by elynema** [comment]
We discussed use a fragmentselector on the canvas (see [example](https://gist.github.com/stephenwf/2c2a7dbf00f6b9777d9515c2ffccc1d0#file-av-json-L29-L33)) with the painting annotation vs. creating a [Range](https://iiif.io/api/presentation/3.0/#overview-range) within the structures with [behavior=sequence](https://iiif.io/api/presentation/3.0/#table-behavior) that targeted a portion of the canvas with the painting annotation ie, `https://example.org/canvas#t=60,120`). The former option is probably not widely supported by players; Stephen Fraser suggested the latter strategy with Range would work in UV.

We prefer the former solution at this time, which will limit the media fragment as it is painted onto the canvas. This matches well semantically with what we a playlist item is (the actual playlist item is the cropped piece of media). It has also been basically implemented in Ramp already.

To match with Ramp's implementation and for simplification, we will use this technique of expressing a fragment of a media item when painting onto a Canvas (note the duration of the Canvas will have to match the duration of the segment):

  ```
{
          "id": "https://iiif.io/api/cookbook/recipe/0002-mvm-audio/canvas/page",
          "type": "AnnotationPage",
          "items": [
            {
              "id": "https://iiif.io/api/cookbook/recipe/0002-mvm-audio/canvas/page/annotation",
              "type": "Annotation",
              "motivation": "painting",
              "body": {
                "id": "https://fixtures.iiif.io/audio/indiana/mahler-symphony-3/CD1/medium/128Kbps.mp4?t=60,180",
                "type": "Sound",
                "format": "audio/mp4",
                "duration": 1985.024
              },
              "target": "https://iiif.io/api/cookbook/recipe/0002-mvm-audio/canvas"
            }
```
The method of addressing a temporal fragment in the URI of the media file itself seems to be supported by other video libraries, like video.js, so if other players are using those libraries, they will automatically play only the identified fragment (even though the whole media item would likely show up in the player). 

As there is not strong support for any of these methods (or even streaming media) across IIIF media players now, this seems like the easiest solution and acceptable for now.
