### ISSUE TITLE
Display Empty Canvases as Inaccessible Items

### ISSUE THREAD

**Issue by joncameron** [samvera-labs/ramp#213]
# Description
Items that are inaccessible to users should still be listed as items within a playlist.

# Done Looks Like
- Items in a playlist manifest without content in the canvas are shown in the structure display as "Inaccessible Item" in the structured navigation
- placeHolderCanvas should be displayed from the manifest, but Ramp player controls should not be accessible to user (since the video can't be played, user cannot create playlist markers, etc.)

**Comment by masaball** [comment]
I got the item message to display and got navigation through the playlist partially working. To get navigation working required initializing an empty version of the VideoJS player for the inaccessible item. There will need to be additional styling work done to finalize it, either initializing the player without rendering anything or getting the inaccessibility message to render within the confines of the player.
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBZzlFIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--40579f36528e701d42636343ccf365d90b62db37/Screenshot_20230828_125625.png)

The structured navigation also only partially works. When a user tries to switch back and forth between an accessible item and an inaccessible item, the navigation eventually breaks and no longer lets the user navigate via the structured navigation. This could potentially be worked around by implementing behavior similar to Avalon's current behavior where a user cannot select restricted items and they are skipped by the autoplay. Or the navigation can be tweaked to handle switching between full and empty canvases.

**Comment by elynema** [comment]
Note that in structured navigation, inaccessible items are displaying a lock, but show the title of the playlist item and are clickable. This is because currently, we change the label for the canvas in the manifest to "Restricted item" (for example), but we don't change the label in the structured navigation. Jon C. agreed we should view how this looks and then decide if we want to change up the structured navigation in the manifest.
