### ISSUE TITLE
Add Auto-advance Component

### ISSUE THREAD

**Issue by joncameron** [samvera-labs/ramp#214]
# Description
From a code perspective it makes sense to have the auto-advance toggle to be a part of Ramp, since the state machine for this is on the Ramp side. It's easier to hook this up to the player state within Ramp rather than via Avalon.

# Done Looks Like
- [x] An auto-advance toggle component for Ramp is added
- [x] Can be a part of structured navigation in the UI
- [x] Auto-advance behavior depends on the state of the toggle

**Comment by cjcolvar** [comment]
The auto-advance toggle button is on the ramp demo page but it doesn't seem to be working.  Autoplay happens even when the toggle is switched off.  I'm testing with this manifest: https://avalon-dev.dlib.indiana.edu/playlists/32/manifest.json

**Comment by elynema** [comment]
Auto-play component is working as expected on the Ramp demo page. @cjcolvar Is the auto-play toggle an independent Ramp component, or is it part of the structured navigation component?

**Comment by cjcolvar** [comment]
@elynema It is an independent component.
