### ISSUE TITLE
Transcript Updates When Current Media Files Changes in Ramp

### ISSUE THREAD

**Issue by joncameron** [samvera-labs/ramp#215]
# Description
When switching between canvases, the transcript component doesn't update quickly as would be expected. It carries information from the previous canvas, and will break if the user interacts with it since it is no longer hooked up correctly.

# Done Looks Like
- [x] Transcript component updates with new information when switching between canvases (files) quickly enough that users can't interact with transcript data from the prior canvas (file)

**Comment by elynema** [comment]
This is working when navigating the structured navigation. I believe it is also working when using prev/next canvas buttons (but those are breaking fairly frequently, so it's hard to get a good test).
