### ISSUE TITLE
Display Only Current Range in Progress Bar

### ISSUE THREAD

**Issue by joncameron** [samvera-labs/ramp#227]
# Description
As as user, I want a progress bar to represent the duration of the current track/segment, rather than the duration of the entire file. Rather than changing the UI, for Ramp in Avalon 7.8 the existing functionality will be copied.

This issue revives #12, replacing "lil' scrub.", which showed the duration of the current track within a separate progress bar that appeared below the original media player. This is for a "track view" that displays the duration of the current track to fit the entirety of the progress bar in the media player, allowing for easier seeking and presentation of tracks present in a single AV stream. This is particularly relevant for audio CDs which have been extracted as a single stream but are meant to be navigated using track metadata.

For this ticket, segment/track/chapter can be used interchangeable to refer to labeled time ranges that define named areas of content within a recording. 

# Done Looks Like
- [x] The media player includes a zoom button that toggles the display of the secondary, segment-level progress bar
- [x] The zoom button does not appear if there are no tracks (no structure except the sections themselves)

When zoomed out (default):
- [x] Clicking the zoom button toggles the presence of the track-level progress bar

When zoomed in:
- [x] A short panel opens below the player with a separate progress bar showing the duration of the currently active track
- [x] The start of the zoomed in progress bar is 0:00 and the end is the duration of the currently active track (rather than the timestamp within the broader media item)
- [x] When autoplay advances from one track immediately to the next track, the zoomed in progress bar reloads to displa
- [x] When the user clicks on a track and the zoomed in progress bar is open, the new duration should reload in the zoomed in progress bar
- [x] When autoplay advances past the end of a track and the content continues but there is no track covering it, the zoomed in progress bar displays the duration of the entire file, instead of the track-level view (matching Avalon 7.6)

# Current Functionality in Avalon 7.6
![Dec-12-2023 09-30-21](https://github.com/samvera-labs/ramp/assets/1406618/791689fc-0389-4a8d-8f45-4dce37b9cf39)

# Notes
- Implementing as a custom component would most likely be easier than trying to create a video.js plug

**Comment by joncameron** [comment]
- Context is a concern (how will users know which zoom level they're at?)
- How will timespans outside of structure data be handled? 
- What happens when the next timespan/section begins?

**Comment by elynema** [comment]
@joncameron I took a stab at starting to update done looks like, but I didn't delete anything that was already there, which still needs to be done. I wanted to make sure we covered all the functional cases in Done Looks Like for QA purposes.

**Comment by elynema** [comment]
@joncameron If this is a custom component, does that mean Ramp users decide if they want it to display? I didn't know if some users might not want this component.I didn't see anything about that in the StyleGuidist docs.

**Comment by joncameron** [comment]
Yes, it should display or not based on values passed in. It's currently suppressed as expected on the /embed page for example.

@Dananji could you update the docs with the new value? Thanks!

**Comment by elynema** [comment]
Li'l Scrub is not working properly in the iPad environment in either Chrome or Safari. That seems to be part of a larger issue in Ramp #354 (https://github.com/samvera-labs/ramp/issues/354) and Ramp #338. It's not available on iPhone mobile device (since the native player doesn't include Li'l scrub). 

On Android, Li'l scrub is not working in Firefox. It works fine in Chrome. Here's a video of it in Firefox:

[Private Zenhub Video](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBd3Z2QWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--f34d29aff392862d91e41821d6eea0988c7e8093/Screen%20Recording%202024-01-23%20at%2010.33.29%20AM.mov)

@joncameron Have you tested this in computer browsers?

**Comment by joncameron** [comment]
I tested all desktop browsers and it worked without issue in Safari, Chrome and Firefox so this seems to be mobile platforms only. I'm comfortable closing this issue because it does seem like part of https://github.com/samvera-labs/ramp/issues/354 and https://github.com/samvera-labs/ramp/issues/338 and will get resolved on those issues.

I'll create a separate issue for it not working in Firefox on Android, since that seems to me like a reasonable "known issue" bug that shouldn't hold back release.
