### ISSUE TITLE
Implement  `no-auto-advance` as default behavior for Canvas resources in Ramp

### ISSUE THREAD

**Issue by Dananji** [samvera-labs/ramp#237]
### Description

The default temporal behavior in a IIIF Manifest is to, `no-auto-advance` (Reference: https://iiif.io/api/presentation/3.0/#behavior)
Therefore default behavior of Ramp to auto-advance to the next available Canvas when playback ends is not the accepted behavior. The default behavior when playback reaches the end of a Canvas or Range is to reset the player and stop playback. This needs to be fixed.

# Question
This looks like it applies to Ranges as well in the spec: `Valid on Collections, Manifests, Canvases, and Ranges that include or are Canvases with at least the duration dimension. When the client reaches the end of a Canvas, or segment thereof as specified in a Range.` Should this be updated to explicitly include ranges as well?

A: No, we'll only focus on Canvas elements for the purposes of this issue, and implement further updates to include Ranges as per the spec as a follow-up.

### Done Looks Like
- [ ] Use `behavior` from given Manifest to determine auto-advance
- [ ] When `behavior` is not specified, stop auto-advance at the end of the current Canvas

### Related
#186

**Comment by joncameron** [comment]
More research needed for handling ranges as opposed to canvases in IIIF.

**Comment by elynema** [comment]
@Dananji The auto-advance behavior works on playlists as specified in the manifest, but it breaks when it encounters an item that is restricted. Have we discussed how that should work?

**Comment by elynema** [comment]
Closing this; will open a new issue for investigating how we want to handle auto-play for restricted items.
