### ISSUE TITLE
[BUG] Auto-advancing to next Canvas

### ISSUE THREAD

**Issue by Dananji** [samvera-labs/ramp#239]
### Description

Ramp with auto-advance turned on; when a media files ends and starts loading the next Canvas into the VideoJS player there's a error logged into the console in the browser 99+ times . This doesn't break the functionality, but the custom VideoJS components seems to be trying to mount before the VideoJS instance is fully initialized.
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBanlQIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--1d8c17d118a5927983c978e63ff4c2eb209db0e7/Screenshot%20from%202023-09-12%2010-29-39.png)

### Done Looks Like
- [ ] Custom components mount wait for VideoJS to be fully initialized
- [ ] No errors are logged into the console

**Comment by elynema** [comment]
Ready for QA in Ramp demo site.

**Comment by elynema** [comment]
Ready for QA in Avalon.

**Comment by charumitraravi** [comment]
QA completed
