### ISSUE TITLE
Expand All/Collapse All for Section Structure

### ISSUE THREAD

**Issue by joncameron** [samvera-labs/ramp#247]
# Description
For first pass implementation, would like ability for a user to be able to expand all sections or collapse all sections using the expand all/collapse button that already exists.

Does Ramp need to provide any additional functionality to enable the expand all / collapse all button in Avalon to work properly? 

# Done Looks Like
- [ ] While a media item is playing, if it is actively playing a section with structure, structure should expand all by default and jump to the actively playing segment.
- [ ] Structure should be expanded by default when media object page loads in Avalon

**Comment by joncameron** [comment]
Re-renders were causing instability in the component, making it difficult to retain the collapsed state. There's a library looked at in coworking time (https://github.com/pmndrs/zustand) that is for subscribing to state events and could be helpful.

This will probably require a refactor to the existing state management in Ramp.

**Comment by elynema** [comment]
From Chris:

Here's what I found with a solr query and computations on the ruby side:
0 number of sections: 500
1 number of sections: 88603                                                                                               
2 number of sections: 69750                                                                                               
3 number of sections: 7409                                                                                                
4 number of sections: 6497                                                                                                
5 number of sections: 916                                                                                                 
6 number of sections: 2805                                                                                                
7 number of sections: 253                                                                                                 
8 number of sections: 854                                                                                                 
9 number of sections: 116                                                                                                 
10 number of sections: 339                                                                                                
11 number of sections: 70                                                                                                 
12 number of sections: 195                                                                                                
13 number of sections: 63                                                                                                 
14 number of sections: 83                                                                                                 
15 number of sections: 51
16 number of sections: 83
17 number of sections: 28
18 number of sections: 49
19 number of sections: 21
20 number of sections: 51
21 number of sections: 17
22 number of sections: 23
23 number of sections: 13
24 number of sections: 54
25 number of sections: 12
26 number of sections: 27
27 number of sections: 11
28 number of sections: 11
29 number of sections: 15
30 number of sections: 4
31 number of sections: 8
32 number of sections: 11
33 number of sections: 6
34 number of sections: 10
36 number of sections: 6
37 number of sections: 6
39 number of sections: 3
41 number of sections: 2
43 number of sections: 4
45 number of sections: 4
47 number of sections: 3
48 number of sections: 5
49 number of sections: 1
52 number of sections: 3
53 number of sections: 1
55 number of sections: 8
56 number of sections: 3
58 number of sections: 1
60 number of sections: 1
61 number of sections: 1
62 number of sections: 1
63 number of sections: 1
66 number of sections: 3
69 number of sections: 4
71 number of sections: 3
72 number of sections: 3
73 number of sections: 1
75 number of sections: 2
76 number of sections: 2
77 number of sections: 1
79 number of sections: 5
81 number of sections: 2
83 number of sections: 3
84 number of sections: 2
86 number of sections: 1
88 number of sections: 3
91 number of sections: 1
96 number of sections: 1
97 number of sections: 1
100 number of sections: 2
101 number of sections: 1
104 number of sections: 2
109 number of sections: 1
112 number of sections: 1
113 number of sections: 1
115 number of sections: 1
117 number of sections: 1
125 number of sections: 1
129 number of sections: 1
130 number of sections: 1
138 number of sections: 1
143 number of sections: 1
153 number of sections: 1
157 number of sections: 2
165 number of sections: 1
169 number of sections: 1
176 number of sections: 1
195 number of sections: 1
203 number of sections: 1
210 number of sections: 2
219 number of sections: 1
234 number of sections: 4
244 number of sections: 1
305 number of sections: 1
358 number of sections: 1
385 number of sections: 1
386 number of sections: 1
415 number of sections: 1
639 number of sections: 1

Adding up those with more than one section:
89984

So 0.3% have no sections, 49.5% have one section, and 50.2% have more than one section. (edited)

**Comment by elynema** [comment]
Having multiple sections does not necessarily require an accordion, unless those section have structure. How many sections actually have structure?

**Comment by joncameron** [comment]
Expand/collapse could be a useful question to pose to users. Does it matter?

**Comment by elynema** [comment]
@joncameron Did we agree to make a first pass at implementation where there is a single button to expand/collapse all sections, rather than having a button for each section? If so, it would be great to pull this into this sprint to try to finish for user testing.

**Comment by elynema** [comment]
@joncameron Checking on this since I'd like to pull it into next sprint. Did we agree to a first implementation that is just expand all / collapse all?
