### ISSUE TITLE
Display source item metadata for playlist items

### ISSUE THREAD

**Issue by elynema** [samvera-labs/ramp#252]
# Description

Part of #5168 in Avalon (to utilize Ramp components on playlist page in Avalon) is to display source item metadata for the playlist item that is included in the IIIF playlist manifest. This is metadata included at the canvas level.

# Questions

- [ ] What if a IIIF manifest has metadata at both manifest and canvas level? We should allow the option for Ramp users to display metadata from both, although IU does not have a use case for that

# Done Looks Like
- [x] Details component reads from either canvas-level or manifest-level descriptive metadata or both
- [x] Ramp has a prop or other method to initialize the Details component telling it whether to read canvas-level, manifest-level, or both levels of metadata
- [x] Details instance on the playlist page uses the Details component with canvas-level metadata

**Comment by Dananji** [comment]
> What if a IIIF manifest has metadata at both manifest and canvas level?

@joncameron Did we answer this question, when we discussed this issue? I don't remember what was the answer. 

Looking at the done criteria, it says `read from either canvas-level or manifest-level descriptive metadata`. I'm not sure this answers it or not :)

**Comment by joncameron** [comment]
Could have 2 props into Ramp that could be turned on and off according to user preference.

**Comment by Dananji** [comment]
Declare input props in the component to read either from Manifest-level or Canvas-level OR both-levels. This way it is customizable according to user preference.

**Comment by elynema** [comment]
Default is to read from manifest level metadata so as not to break anything. 2 new props that allow to specify only canvas level metadata or both canvas and manifest level metadata. See details in PR.

**Comment by elynema** [comment]
Ok to handle the case of no source item metadata this way?

<img width="1207" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBKysyQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--0c5b79fd8122111c8f6d67ce00fb94d575f73c64/image.png" alt="image.png" />
