### ISSUE TITLE
Fix Rollup build with dynamic imports using code-splitting

### ISSUE THREAD

**Issue by Dananji** [samvera-labs/ramp#254]
### Description

Ramp uses dynamic imports to load the relevant language maps from VideoJS for selected language within the component. This code breaks the rollup bundling process.

### Done Looks Like
- [ ] Rollup successfully bundles the library with dynamic imports

### Notes
Possible solutions investigated;
- https://www.npmjs.com/package/@rollup/plugin-dynamic-import-vars -> cannot be used with absolute path/bare import
- cannot use `inlineDynamicImports` with the existing output structure

Resources;
- https://rollupjs.org/tutorial/#code-splitting
- https://rollupjs.org/configuration-options/
- https://github.com/rollup/rollup-starter-code-splitting

**Comment by elynema** [comment]
This is required if we want internationalization in Ramp for 7.7 release. If not, then we could leave this.
