### ISSUE TITLE
[BUG] Prev/next canvas buttons break

### ISSUE THREAD

**Issue by elynema** [samvera-labs/ramp#258]
# Description

For some records the prev and / or next canvas buttons in the Ramp media player cause the screen to go blank and generate null pointer errors in the developer's console. Dananji thinks it's a bug with markers used in VideoJS to highlight  the structure in the progress bar.

Note that this does not necessarily happen when navigating between *every* canvas on the media object.

Here is an example of what happens after clicking on prev and / or next.

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNmNOQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--0d4cdf51372abb3a7bdc92756833de4a00c24fc2/image.png)

# To Reproduce

Here are some example records that have this issue as you use the prev / next canvas buttons:

- https://avalon-dev.dlib.indiana.edu/media_objects/3n203z084
- https://avalon-dev.dlib.indiana.edu/media_objects/000000000
- https://avalon-dev.dlib.indiana.edu/media_objects/m900nt40f (note, this has multiple sections, but no structure?)

# Environment

Mac OS laptop, Chrome, avalon-dev

# Release

 Avalon 7.7

**Comment by elynema** [comment]
Could be a simple check to see whether there is structure or it could be some type of merge conflict.

**Comment by elynema** [comment]
Ready to QA on avalon-dev.

**Comment by charumitraravi** [comment]
I performed QA on the 3 items mentioned in the bug, and there were no issues. 
Although, I could still find the null pointer issue happening for the 4th section in this item - https://avalon-dev.dlib.indiana.edu/media_objects/g158bh28p - and the page becomes blank 
@Dananji @elynema

**Comment by elynema** [comment]
@charumitraravi @Dananji I believe that is a known issue -- the third section on that item is missing derivatives; there is a placeholderCanvas message in the IIIF manifest, but Ramp is not displaying that yet.

Charu, are you sure it's the 4th section? I had the issue with the 3rd section.

**Comment by charumitraravi** [comment]
@elynema It is the 3rd section. Thanks for noting it.
