### ISSUE TITLE
[BUG] Canvas level items in Structured Navigation are always rendered as buttons

### ISSUE THREAD

**Issue by Dananji** [samvera-labs/ramp#259]
### Description

In the new structured navigation UI, all the canvas level structure items are displayed as clickable buttons regardless they have media fragment related information attached to them. When there are no media fragment related to the item, the click event won't do anything.

Although IU may always provide media fragments for canvas level structure items, the same may not be true of other institutions using Ramp.

### Done Looks Like
- [ ] Only use buttons for Canvas level structure items when there's media fragment (canvas related info) is available
- [ ] Canvas level items without media fragment information are displayed as a title without a button
- [ ] Section-level structure should only appear clickable if clicking on it actually does something in the player.

**Comment by elynema** [comment]
Ready to QA on avalon-dev

**Comment by charumitraravi** [comment]
QA completed. The items in the "Done looks like" column is verified
