### ISSUE TITLE
Auto-play behavior for restricted items

### ISSUE THREAD

**Issue by elynema** [samvera-labs/ramp#261]
# Description

In Ramp's current implementation of the IIIF auto-advance directive, if the auto-advance encounters a restricted item in a playlist, it stops. In the current implementation of playlists in Avalon, restricted items are skipped and auto-play moves on.

Does Ramp need to skip restricted items? Ramp should probably display restricted/inaccessible items, since this would honor the back/forward buttons that go back and forth between items. It's more likely in the playlist case that something is restricted. Could we handle this in the playlist scenario, rather than trying to model this in a way that is handled identically. Probably not a pressing issue for 7.7.

We can come back to this after 7.7; the current behavior should be tenable in most real world scenarios.

**Comment by Dananji** [comment]
Ramp's current behavior: when auto-play is turned on, Ramp plays through the items and renders an empty player canvas for the inaccessible item but doesn't display the message. But displays the message when clicked on the inaccessible item structure item in the structured navigation.

**Comment by elynema** [comment]
In #269, this is resolved in the playlist scenario. Auto-play moves through the restricted items, giving them a brief display. They can be selected if auto-play is turned off, and the error message displays to the user but the section remains selected.

Are any changes needed for items that are inaccessible on the media object page (ex: uploading or derivative unavailable)?

**Comment by elynema** [comment]
@joncameron Can you review this to determine if this work is completed or you feel more work is needed?

**Comment by joncameron** [comment]
I think this has been covered by other work including https://github.com/samvera-labs/ramp/issues/269 and can be closed.
