### ISSUE TITLE
Canvas level labels in structured navigation should be navigable

### ISSUE THREAD

**Issue by elynema** [samvera-labs/ramp#265]
# Description

Currently, Section level labels in the structured navigation component only provide a link back to play the Canvas if the structures section for the first item in the Range for that Canvas has a media fragment linking back to the full canvas.

Can we implement something similar for Ranges where there is structured navigation with canvas-level fragment links? Otherwise, the section label itself in the structured navigation does not provide the user with a link to resume playback at the start of the Canvas.

Is this a change within Ramp (how it reads in data in the structured nav to generate links back to play the Canvas) or a change in Avalon to generate manifests with Canvas level links?

Here is what the structures section looks like for a section with no structure created. It does provide a link back to play the entire Canvas on the Ramp demo site:

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBL1VuQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--b398fa1199502db23c310224ad2ed9ea5c1f77b6/image.png)

Item: https://avalon-dev.dlib.indiana.edu/media_objects/g158bh28p/manifest.json

**Comment by joncameron** [comment]
Can we add a full canvas reference for every item?

**Comment by joncameron** [comment]
- Make a test manifest that has an element that represents the canvas at the top level
- Test with other viewers to see how they parse this

**Comment by Dananji** [comment]
I edited one of the cookbook manifests to include a Canvas reference into the Canvas level Range, like we expect to implement in Avalon: [https://gist.github.com/Dananji/6743f7f594ac4f7de17d1c03427b08e8](https://gist.github.com/Dananji/6743f7f594ac4f7de17d1c03427b08e8)
I tested this in Clover, Mirador, and UV and they all parses the Manifest without any issues. For UV the addition of the Canvas reference to the canvas-level Range doesn't change anything with the navigation.

**Comment by joncameron** [comment]
Can this changed to an implementation ticket if Done Criteria are added? This can be changed to an avalon ticket, and then checked on the Ramp side.

**Comment by elynema** [comment]
Closing this; opened #5451 for Avalon-side implementation.
