### ISSUE TITLE
[BUG] Display inaccessible message when auto-play is on

### ISSUE THREAD

**Issue by Dananji** [samvera-labs/ramp#269]
### Description

When auto-play is turned on Ramp plays through items in a playlist manifest, and displays an empty player for an inaccessible item. But doesn't show the message in the `placeholderCanvas`. But when clicked on the inaccessible item in the playlist items list in the structured navigation, the message is displaying.

### Done Looks Like
- [x] Displays the message in the `placeholderCanvas` when auto-playing or when user selects a restricted playlist item
- [x] Advance to the next Playlist item after a set amount of time (Ramp variable defaulted to 3s)
- [x] Count-down of 3 seconds on restricted item should begin whenever auto-play is turned on, even if the user clicks directly on the restricted item in the playlist.

**Comment by elynema** [comment]
@Dananji For first implementation, it is fine for playlists to continue to auto-advance, even if user clicks on an item in the structured navigation. How does this impact structured navigation implementation on the media object page? Do those continue to auto-advance after the user selects a specific section?

**Comment by elynema** [comment]
@Dananji Added a done looks like criteria to this and moving it back to in progress.

**Comment by elynema** [comment]
This looks good on Ramp demo site. We may possibly want to make it more like 4-5 seconds, but I think it's good for a first iteration.
