### ISSUE TITLE
Retain Focus After Selecting Next or Previous Buttons

### ISSUE THREAD

**Issue by joncameron** [samvera-labs/ramp#274]
# Description
When a user uses the keyboard to focus on the previous or next buttons and selects them by pressing enter, the context of the currently selected element is lost. Ramp should retain the current focused element when events occur within the components.

# Done Looks Like
- [x] Focus is retained on previous and next canvas buttons in media player after they are selected and events occur

# Current Behavior
https://github.com/samvera-labs/ramp/assets/1406618/9d1ab488-972c-4ab7-8311-a42a2fa2f032

**Comment by joncameron** [comment]
There may be video.js properties we can use here.

**Comment by Dananji** [comment]
Not in `avalon-dev` yet, but can be tested on the Ramp demo site.

**Comment by charumitraravi** [comment]
QA completed on avalon dev
