### ISSUE TITLE
Display Error Message for Critical Errors Where Ramp Cannot Render

### ISSUE THREAD

**Issue by joncameron** [samvera-labs/ramp#280]
# Description
Current Ramp doesn't render any components when encountering certain error states. This can happen for errors that happen in any component in the app.

React ErrorBoundaries could be used in Ramp to capture errors bubbling up from children components and could be given a message to display. We could do this on the Ramp side, to avoid the issue of nothing rendering, whatever the error within Ramp is.

# Done Looks Like
- [x] Critical errors result in an error message being rendered to the user, instead of a blank on the containing page element.
- [x] Message: "This page encountered an error. Please refresh or contact an administrator."

**Comment by elynema** [comment]
@Dananji Can you think of a good way to QA this?
