### ISSUE TITLE
[BUG] All Timespans are Highlighted for a Canvas/Section

### ISSUE THREAD

**Issue by Dananji** [samvera-labs/ramp#281]
### Description

In Avalon manifests we have Canvas information for each Range at a section level, and this creates a navigable structure item for Ramp's structured navigation component.
With this change, Ramp's structured navigation looks like in the image for timestamps where there are no child timespans in the structure;
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeXU1QVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--01a76908acd38593d60e8d6cae8fdc04a4b43c0c/image.png)

This probably should not highlight all the timespans? And highlight the entire time-rail (progress bar)?

**Comment by Dananji** [comment]
Fixed by https://github.com/samvera-labs/ramp/pull/284

**Comment by joncameron** [comment]
Needs to be retested to confirm it's fixed by #284 and working in Avalon.
