### ISSUE TITLE
Force scrollbar to display in Firefox for structured navigation

### ISSUE THREAD

**Issue by elynema** [samvera-labs/ramp#287]
# Description

For users to understand that the new structured navigation is scrollable, there really needs to be a visible scrollbar. We have forced the scrollbar to always appear in Safari and Chrome (see #5429). However, Firefox does not seem to respect webkit styling.

Since it seems like forcing a scrollbar would introduce a lot of overhead, we may be able to use some other UI cues for Firefox users:
- lightly colored bounding box around the structured navigation component
- floating "To top" and "To bottom" links/elements

# Done Looks Like
- [x] Investigate options other than scrollbar for user navigation of the structured metadata navigation component

**Comment by masaball** [comment]
A boundary box by itself does not always provide enough of a cue that there is more content that can be seen by scrolling:
<img width="619" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeGxOQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--55c45adf72a2ce3e8a7f972b7af4a8373b4dd10a/Screenshot_20231211_113417.png" alt="Screenshot_20231211_113417.png" />

I do think it would be good to add the boundary box regardless, to provide more visual context to the page. Regardless, one approach we could take is to provide a fade out towards the bottom of the structured nav:
<img width="588" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeU5OQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--37e82e00da1f46ae7ba05b943b803f8aa203d2c2/Screenshot_20231211_134225.png" alt="Screenshot_20231211_134225.png" />

We would need to have some code in place for when the end of the scrollable element is reached to turn off the fading. Also, we would need to make sure the fading is only turned on in the first place when the element is actually scrollable.

Another approach would be to have a message at the top or bottom of the element that informs a user that there is scrollable content:
<img width="585" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeVZOQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--f6539a438477c142460ab782f737e626598ddd3b/Screenshot_20231211_141929.png" alt="Screenshot_20231211_141929.png" />

Chris' suggestion of the floating "To Top"/"To Bottom" links would be visually similar to this last option, but would have the added behavior of taking the user to the top/bottom of the scrollable area when the link is clicked on. For the "Scroll to see more" option, different wording and styling of the message can be decided on. As with the fade option, we would want logic to turn off the message when the element is not scrollable and for when the end of the element is reached.

We can also combine any of these approaches.

**Comment by elynema** [comment]
I believe that @joncameron provided feedback for me that he'd like to combine these approaches. I will create a new ticket.

**Comment by elynema** [comment]
See #335 for actual implementation of this proposal.
