### ISSUE TITLE
Collapse All Not Functional During Media Playback

### ISSUE THREAD

**Issue by joncameron** [samvera-labs/ramp#293]
# Description
During media playback, selecting the "Collapse All" button quickly closes and reopens the structural navigation area for sections with structure.

[Refer to Charu's [Screen recording](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOWZLQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--06dc28c6168dd6b3d930c679c9e807660fc3fefb/Expand-collapse%20button.mov)]. 

See comments on https://github.com/avalonmediasystem/avalon/issues/5379.

# Done Looks Like
- [ ] Selecting "Collapse all" during playback collapses the structural metadata area for all sections with structure

**Comment by joncameron** [comment]
Pause on this until state management refactoring in Ramp.

**Comment by elynema** [comment]
Every time a new track/segment beings to play, Ramp will re-open the structure, as we've asked that the structure open automatically if a track is playing.

**Comment by joncameron** [comment]
No longer a problem in Ramp 3.3.
