### ISSUE TITLE
Error When Navigating Tabs with Arrow Keys

### ISSUE THREAD

**Issue by joncameron** [samvera-labs/ramp#294]
# Description
When focus is on the headings in the tabbed navigation, users can use the left and right arrow keys to move focus between each set of the tabbed items as specified in #273. When the keyboard is pressed once too far to the left or right of the row, where a user would generally expect to return to the opposite side of the array of tabbed items, the tab body area is blank and focus is doubled on the first or last entry in the tabbed list.

# To Reproduce
- Move focus using the keyboard to the labels of the tabbed components (Details, Transcripts etc.)
- Use the arrow keys to go through the list, both forward and backward 
This error should pop up in the console:
`Uncaught TypeError: n[r] is undefined`

# Done Looks Like
- [x] Focus wraps appropriately when using arrow keys to navigate between tab sections (Details / Transcripts / Files)
  - [x] left arrow key event, when focus is on the first the list, moves focus to the last in the list
  - [x] right array key event, when focus is on the last in the list, moves focus to the first in the list

**Comment by charumitraravi** [comment]
QA completed. The  arrow switch in the  (Details / Transcripts / Files) tab section is working as expected. 
Although, there is an issue when there is no transcript tab, in which case, the arrow button shows a non existent transcript tab section. (Refer [screen recording](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNUluQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--de30a04d7a297623d565b875dbb131ae50c39f98/Screen%20Recording%202023-12-01%20at%201.52.46%20PM.mov))

**Comment by joncameron** [comment]
Pulling this back into Code Review since this is still occurring as in Charu's recording, where it seems like the transcript tab is still being selected for display behind the scenes.

**Comment by Dananji** [comment]
This is a separate issue unrelated to the one fixed in this ticket. The issue in this ticket is related to the Ramp demo site not Avalon. The tabs in the Ramp demo site and tabs in Avalon's item page are 2 different implementations.
@joncameron Let's close this and create a new ticket for the Avalon issue.

**Comment by joncameron** [comment]
Created https://github.com/avalonmediasystem/avalon/issues/5520; closing this one as resolved.
