### ISSUE TITLE
[BUG] Transcript component sometimes get stuck on transcript from another canvas

### ISSUE THREAD

**Issue by elynema** [samvera-labs/ramp#296]
# Description

Sometimes, the transcript component from Ramp on the media object page can seem to get stuck on a transcript from one canvas. When switching to another file (canvas), it may retain the prior transcript display. It seems to happen regardless of whether the new canvas has its own transcript or not.

It is possible this bug is related to a specific item. Only replicated so far with this specific item: https://avalon-dev.dlib.indiana.edu/media_objects/g158bh28p

First select section #3 (Cat in Slo Mo). This section has a transcript in .docx format. The transcript does not appear. Note: this item seems to be missing its streaming derivative, so possibly that could be causing issues in the transcript component?

Next select section #2 (lunchroom_manners.mp4). Now the .docx transcript for section #3 displays. The transcript for section #2 does not display.

Note: if you reload the page, and click first on section #2, the correct transcript does display.

I have not been able to replicate this issue on another record with transcripts for each section, which makes me wonder if the section missing a streaming derivative is causing a larger problem: https://avalon-dev.dlib.indiana.edu/media_objects/gf06g267d

**Comment by joncameron** [comment]
Maybe a hook that's not firing which is expected, which could be creating errors.

**Comment by elynema** [comment]
To fully resolve this, need to investigate how to roll up a small video file into the NPM package.

**Comment by elynema** [comment]
I'm not able to replicate this currently across Chrome, Safari, and Firefox on my laptop.
