### ISSUE TITLE
Auth credentials for Marker component

### ISSUE THREAD

**Issue by masaball** [samvera-labs/ramp#298]
## Description
When working on the Marker component we were hardcoding in the API key to carry out PUT/POST/DELETE requests for testing. We removed the API keys from the PR but did not switch to other forms of auth: 

- [IIIF Wrapper](https://github.com/samvera-labs/ramp/blob/70f864c6fd30564d2546897b1a970c701e5e59e4/src/components/IIIFPlayerWrapper.js#L23)
- [Create](https://github.com/samvera-labs/ramp/blob/70f864c6fd30564d2546897b1a970c701e5e59e4/src/components/MarkersDisplay/MarkerUtils/CreateMarker.js#L39)
- [Edit](https://github.com/samvera-labs/ramp/blob/70f864c6fd30564d2546897b1a970c701e5e59e4/src/components/MarkersDisplay/MarkerUtils/MarkerRow.js#L75)
- [Delete](https://github.com/samvera-labs/ramp/blob/70f864c6fd30564d2546897b1a970c701e5e59e4/src/components/MarkersDisplay/MarkerUtils/MarkerRow.js#L117)

I'm not sure but making these changes could potentially solve the CSRF issues in Avalon [#5485](https://github.com/avalonmediasystem/avalon/issues/5485)?

## Done Looks Like
- [ ] Change the request headers for Marker actions to `credentials: 'same-origin'`
- [ ] Change the IIIF wrapper request options to `credentials: 'include'`
- [ ] Test in Avalon that playlist marker actions are successful

**Comment by joncameron** [comment]
Create/edit/delete on avalon-dev was successful in my testing.
