### ISSUE TITLE
[BUG] English option under closed captions doesn't work

### ISSUE THREAD

**Issue by elynema** [samvera-labs/ramp#299]
# Description

When closed captions are available in Ramp, one of the options is labeled 'English'. Selecting this option doesn't seem to turn on any closed captions. Since the filename option for captions is available, it seems like the 'English' option is duplicative and should be removed.

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBemNWQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--6493f178db04c2ea9c3cd0a29bfbd48b6920d62c/image.png)

**Comment by charumitraravi** [comment]
QA completed. 
The "English" option is not showing under the captions. And the captions icon option is showing only for items having captions. 
Although, I do find 2 instances of the same caption showing up in the options, Is this expected?
<img width="400" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBM0phQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--ebfb815f1e9a3857d8f6cda5dcc98a1b29fb2926/Screenshot%202023-12-13%20at%2012.48.07%20PM.png" alt="Screenshot 2023-12-13 at 12.48.07 PM.png" />

Also, on an unrelated note, I could see that the transcripts tab is shown for items without transcripts and the transcripts tab is not showing for some items with transcripts, in both cases where the player advances to the next section and when I manually switch between sections. 
https://avalon-dev.dlib.indiana.edu/media_objects/kw52j8067  and https://avalon-dev.dlib.indiana.edu/media_objects/g158bh28p- are  good examples to check this behavior 
This behavior is intermittent and doesn't happen every time.

**Comment by elynema** [comment]
@charumitraravi Yes, there is a bug where captions are showing up twice in the list. That should be resolved with a new Ramp build, hopefully today: https://github.com/samvera-labs/ramp/issues/295

The other issue you reported needed to be its own bug report, so I created https://github.com/avalonmediasystem/avalon/issues/5529.
