### ISSUE TITLE
Change Text When No Markers Exist

### ISSUE THREAD

**Issue by joncameron** [samvera-labs/ramp#303]
# Description
The text users see when there are no Markers in the manifest is confusing in some contexts, like the Avalon playlist page. This text could be excised or updated to be more clear.

# Done Looks Like
- No text appears in the Markers panel when there are no Markers in a playlist manifest (only the Add Mark button display appears)

**Comment by elynema** [comment]
My preference is just to have the Add Marker button display in the component with no error message if there aren't markers.
