### ISSUE TITLE
Use Captions Files in Manifest Instead of From HLS Manifest

### ISSUE THREAD

**Issue by joncameron** [samvera-labs/ramp#308]
# Description
Ramp should respect captions in the IIIF manifest and use those to populate the list shown within the media player, not the HLS manifest. HLS manifest captions were added for the native iOS player, which is used by default when playing a media item on an iOS device (so Ramp is not in use in that context).

# Done looks like
- [ ] all available caption files display once for user selection on mobile devices (particularly iOS)
- [ ] all available caption files display once for user selection on the web

**Comment by elynema** [comment]
@joncameron I believe this is a duplicate that was resolved in Ramp #295.

**Comment by joncameron** [comment]
Duplicate; closing.
