### ISSUE TITLE
IIIF caption/subtitle cookbook recipe no longer works in Ramp

### ISSUE THREAD

**Issue by elynema** [samvera-labs/ramp#325]
# Description

The IIIF cookbook has a recipe for providing a caption/transcript file in a supplementing annotation as a vtt file.

https://iiif.io/api/cookbook/recipe/0219-using-caption-file/

Loading this in the Ramp demo site, the vtt file no longer loads to display as transcripts and captions in Ramp. https://ramp.avalonmediasystem.org/?iiif-content=https://iiif.io/api/cookbook/recipe/0219-using-caption-file/manifest.json

Could this be related to our work to have Ramp recognize captions and transcripts specifically coming out of Avalon using the id of the annotation body?
https://github.com/avalonmediasystem/avalon/pull/5226

**Comment by elynema** [comment]
Re-test captions in playlists, media items, and mobile devices again, as well as with cookbook examples. This involved a change to how we prevent duplication of captions between HLS manifest and IIIF manifest captions.

**Comment by joncameron** [comment]
Captions aren't loading on the Ramp demo page for me on iOS for https://ramp.avalonmediasystem.org/?iiif-content=https://iiif.io/api/cookbook/recipe/0219-using-caption-file/manifest.json. They don't appear within the player, either before playback or in full-screen/native player mode.
@Dananji 

Screenshot of console:
<img width="532" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBL3dDQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--728c7ed83c08718a79e3753d8d4622810f005929/Screenshot%202024-01-26%20at%2011.54.16%E2%80%AFAM.png" alt="Screenshot 2024-01-26 at 11.54.16 AM.png" />

**Comment by elynema** [comment]
Both transcripts and captions are loading properly in Chrome.

In Safari, the transcript loads, but there is no CC icon in the player. I see the same console error that Jon posted above.

In Firefox, the captions load, but the transcript component is empty. The console seems to think it is a permissions issue. Not sure if this is unique to my browser configuration or happening for everyone.
`Security Error: Content at https://ramp.avalonmediasystem.org/?iiif-content=https://iiif.io/api/cookbook/recipe/0219-using-caption-file/manifest.json may not load data from https://fixtures.iiif.io/video/indiana/lunchroom_manners/lunchroom_manners.vtt.`

@Dananji I'm moving this back to In Progress so we can at least take another look at it.

**Comment by joncameron** [comment]
Test results:
Chrome on Android: Captions display in the player and also during fullscreen
Firefox on Windows: Captions display as expected, transcript component loaded successfully
Safari on macOS: Captions display as expected

**Comment by elynema** [comment]
@joncameron Because Safari on iOS uses the native player, I don't believe it is possible for us to support captions in full screen mode because that requires HLS captions. We have no guarantee that a IIIF manifest also has HLS captions?
