### ISSUE TITLE
Include rights and requiredStatement in metadata display component

### ISSUE THREAD

**Issue by elynema** [samvera-labs/ramp#331]
# Description

This suggestion comes from the January IIIF A/V community call. For those who use rights and requiredStatement, they would probably like to have those displayed in the metadata component.

requiredStatement MUST be displayed, so that's a IIIF requirement.

rights is intended to be a machine-actionable uri, so we probably don't need to include that in metadata display: https://iiif.io/api/cookbook/recipe/0008-rights/

# Done Looks Like
- [x] Add a heading at the end of the Metadata that says "Rights" like how Mirador does it. If they exist, requiredStatement and rights could show up below that.
- [x] requiredStatement added to descriptive metadata display component
- [x] rights added as a URI to the metadata display component (with label of "License")

**Comment by elynema** [comment]
Aviary utilizes the requiredStatement: https://weareavp.aviaryplatform.com/iiif/hm52f7jz70/manifest or https://yalemssa.aviaryplatform.com/iiif/028pc2tq0m/manifest

**Comment by elynema** [comment]
Dananji has styled this to be similar to Mirador.

**Comment by Dananji** [comment]
This can be tested on Ramp demo site.

**Comment by elynema** [comment]
@Dananji Do you have an example of an accessible manifest you were using for test that has these components?

**Comment by Dananji** [comment]
I used the demo manifest in Ramp which only has the changes in local dev environment. 
Maybe we could use the Aviary manifests in the above comment?  
- https://ramp.avalonmediasystem.org/?iiif-content=https://weareavp.aviaryplatform.com/iiif/hm52f7jz70/manifest.json
- https://ramp.avalonmediasystem.org/?iiif-content=https://yalemssa.aviaryplatform.com/iiif/028pc2tq0m/manifest.json

**Comment by Dananji** [comment]
An example from Norhtwestern: https://ramp.avalonmediasystem.org/?iiif-content=https://api.dc.library.northwestern.edu/api/v2/works/f764ea7c-9167-4cef-a5f2-221627d37e05?as=iiif

**Comment by elynema** [comment]
This is working fine for the examples Dananji listed.

@Dananji is the code pulling in the label in the requiredStatement as the display label? All the examples listed here use the label "Attribution" so it's hard to tell.

**Comment by Dananji** [comment]
Yes the labels in the `requiredStatement` are used in the display.
