### ISSUE TITLE
Playlist manifest with no items is generating error message

### ISSUE THREAD

**Issue by elynema** [samvera-labs/ramp#339]
# Description

Playlist manifest is generating with empty items[] (see https://avalon-dev.dlib.indiana.edu/playlists/39/manifest.json), but now an error is showing across all browsers (looks like it's coming from Ramp). The goal was for the playlist page to display a message "The playlist is empty" below the playlist title, instead of an error message. See details on https://github.com/avalonmediasystem/avalon/issues/5504

Firefox
<img width="1283" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBelMrQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--153d49ef391a35ec541b219ff39d44c69482de8b/image.png" alt="image.png" />

Chrome
<img width="1209" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBek8rQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--0bf5de49a821184d76d2d48427c4460a34bdf94c/image.png" alt="image.png" />

In the Ramp demo site, it gives a more generic error. 
<img width="1283" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBem0rQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--0853a39ac7fa624ba387097847525c03bdd1b4bc/image.png" alt="image.png" />

# Questions
- [ ] Is this an issue with Ramp or an issue with Avalon? The message that was listed in Done Looks Like doesn't necessarily sound like a generic message that we would display in Ramp, since playlists are a uniquely Avalon concept.

# Done Looks Like
- [x] Message displays to user: "This playlist is empty."

**Comment by joncameron** [comment]
Console errors indicate that an additional check would resolve this.

**Comment by elynema** [comment]
This looks good in Chrome, Safari, and Firefox on laptop, iPhone, and Android.
