### ISSUE TITLE
[BUG] Next canvas button does not work on next to last canvas

### ISSUE THREAD

**Issue by elynema** [samvera-labs/ramp#349]
# Description

If the user is on the next to last canvas (or has selected within the structured navigation for that canvas), the next canvas button in the media player does not do anything. This occurs both for item and playlist manifests, both in the Ramp demo site and for Ramp within Avalon.

Same results in both Chrome and Safari

# To Reproduce
- Go to https://avalon-dev.dlib.indiana.edu/media_objects/fn106x94r
- Click the Next button (either during media playback or before)
- The next section is not loaded into the player as expected

# Done Looks Like

- [x] Next button goes to next canvas, even if next to last canvas (or any structure within that canvas) is selected
- [x] Next button does nothing if the final canvas (or any structure within that canvas) is selected

**Comment by elynema** [comment]
Looks good in Safari, Firefox, and Chrome on macOS laptop. Looks good on Android Chrome and Safari.

**Comment by joncameron** [comment]
Tested on desktop and mobile and the Next button is working as expected.
