### ISSUE TITLE
[BUG] Media player issues in Chrome and Safari on iPad

### ISSUE THREAD

**Issue by elynema** [samvera-labs/ramp#354]
# Description

iPads do not default to opening the native player like iPhones do.

In Safari on the iPad, we are seeing the same player we do in Safari on a computer, both in non-full screen and full screen mode. It is being non-responsive / very laggy when attempting to scrub through the progress bar in particular. That could potentially be resolved by fixing the issue we are seeing in Safari on computer in Ramp #338. samvera-labs/ramp#338

In Chrome on an iPad, it will play non-full screen in Chrome with the video.js player, but if you open full screen it appears to try to leverage the native player. Unfortunately, the scrubbing and other buttons in the non-full screen player in Chrome on the iPad are also showing huge latency / unresponsiveness. After a few attempts to scrub, the media player controls sometimes disappear and then don't come back for many seconds when I click on the video. The native player on iPad is also unresponsive when attempting to scrub, jump forward/back. If I attempt to scrub, then the player stops responding to play/pause, etc. The current time in the progress bar seems to get stuck, even when video is playing.

The non-responsiveness is also happening in li'l scrub, as well.

I attempted a video of the issues in Chrome on an iPad,  but it's probably best to experiment with it directly in Browserstack.

[Private Zenhub Video](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOVB1QWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--50d74d229ee8c60f43c64751f0e256f9085e2a80/Screen%20Recording%202024-01-23%20at%208.59.10%20AM.mov)

# Done Looks Like
- [x] Users can scrub using the progress bar in both Safari and Chrome on iPad in non-full screen mode
- [x] Users can scrub using the progress bar in both Safari and Chrome on iPad in full screen mode
- [x] Users can use the skip forward / back buttons in the native player in Chrome on iPad in full screen mode
- [x] The current time playhead advances properly in both Safari and Chrome even with scrubbing
- [x] Users can scrub using li'l scrub in Safari and Chrome on iPad in non-full screen mode
- [x] Transcript follows scrubbing in the progress bar in Safari on iPad in non-full screen mode

**Comment by joncameron** [comment]
The timeupdate event has been buggy in some contexts, and sometimes stops working in the browser. This could be the case here since all of the affected events are being set by timeupdate. Could be something in the code there which is breaking.

**Comment by joncameron** [comment]
Needs to be retested after changes in Ramp now brought into Avalon.

**Comment by elynema** [comment]
The resolution of #338 (media player lag in Safari) did not resolve issues with Safari on iPad fully. Dananji suggests there may be a need to add touch event handlers to the Ramp progress bar for that?

In Safari on iPad, I am sometimes seeing the page crash after scrubbing back and forth, sometimes just lagging when I click ahead and back in the progress bar, and then sometimes the current time will freeze while the video plays. These problems seem to be worse when a transcript is visible.

**Comment by elynema** [comment]
Browserstack is struggling to recognize touch points, so Dananji is having to test this in physical devices. Dananji will test again this afternoon to see if some changes have improved.

**Comment by Dananji** [comment]
@elynema If you'd like this can be tested on Ramp demo site now to see whether there are any changes are needed before we pull these change into Avalon.

**Comment by elynema** [comment]
I am fine with how auto-scroll is working. Tested only in Chrome on Mac and Chrome/Safari on iPad so far.

I've tested Safari and Chrome on iPad using the Done Looks Like and found 2 issues:

1. The progress bar fades away when playing in non-full screen in Safari after 1-2 seconds. I thought we disabled that?
2. In Safari, the current time bubble in Li'l Scrub gets stuck on whatever time you first clicked on when scrubbing. See video:

[Private Zenhub Video](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBN2dsQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--725f8941d860fd1ab5e0f0935c80d9816674262f/Screen%20Recording%202024-02-02%20at%201.47.56%20PM.mov)

Do you want to look at either of those before we pull these into Avalon for full testing?

**Comment by joncameron** [comment]
I tested all points and couldn't reproduce what Emily was running into in her last comment so I think this one is ready to be closed.
