### ISSUE TITLE
[BUG] Media files play without audio in Chrome on Android devices

### ISSUE THREAD

**Issue by elynema** [samvera-labs/ramp#355]
# Description

Using the Chrome browser on Android devices, there is no audio with video or audio file playback. Chrome works fine on computers and on iOS devices.

In Chrome on Android devices, the video.js player is being used, rather than a player native to the device.

Timeboxed for initial investigation time; can expand this ticket if it's a larger issue.

# Done Looks Like
- [ ] Chrome on Android plays back audio as expected for video and audio items

**Comment by joncameron** [comment]
First step: testing on a physical Android device to make sure it's not a browserstack issue. If not browserstack-specific, could be difficult to track down.

**Comment by masaball** [comment]
I have tested this on my personal phone: Samsung Galaxy s22, Chrome version: 121.0.6167.101. Both audio and video files played back with audio just fine.

If someone else is able to confirm that would be good but I think this is in fact an issue with BrowserStack.

**Comment by masaball** [comment]
@elynema found this browserstack documentation confirming that audio is not supported on Android Chrome

https://www.browserstack.com/question/39397

Closing
