### ISSUE TITLE
Transcript content is contained within a div with role=list

### ISSUE THREAD

**Issue by elynema** [samvera-labs/ramp#357]
# Description

Container element is empty
Some roles are designed to contain other roles. This element has this type of role, but it doesn't contain any Opens in new tab:required-owned elements.

This is flagging on the transcript display 

role = "list"

The content on the transcript tab is contained within a div that has role="list", but the content itself is not a list.

<div class="transcript_content " data-testid="transcript_content_1" role="list" aria-label="Attached Transcript content">

Within this div, the transcript is a series of links, not a list.

<img width="1139" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBK2J4QWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--2b723cfc922590d4209c3a15730e9f7764d7cd89/image.png" alt="image.png" />

**Comment by joncameron** [comment]
Cues in the transcript display can be set as list items in the markup.

**Comment by joncameron** [comment]
Cues in the transcript display can be set as list items in the markup.
