### ISSUE TITLE
Last playlist item title in structured nav blinks bold when last item finishes playing

### ISSUE THREAD

**Issue by elynema** [samvera-labs/ramp#370]
# Description

Once a playlist with auto-play set to true finishes playing the last item in the playlist, the playlist item title in the structured navigation flashes bold in and out repeatedly. Looks as if Ramp thinks it should be highlighted as active item then un-does the highlighting.

[Private Zenhub Video](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNElnQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--8a06d02411d6304e21c6bee38e9859022bbb8e77/Screen%20Recording%202024-02-01%20at%205.46.44%20PM.mov)

**Comment by joncameron** [comment]
Also needs retesting since a new Ramp build has since been added to Avalon.

**Comment by elynema** [comment]
Re-tested and still seeing this issue. It blinks bold in Chrome, but in Safari and Firefox, it is much worse, as the enter list of playlists items starts flashing.


[Private Zenhub Video](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBd0VzQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--c778481da2adadef914aa3b56b50baa797b64f90/Screen%20Recording%202024-02-05%20at%2011.20.09%20AM.mov)

**Comment by elynema** [comment]
@masaball I'm still seeing some flashing in Safari on Ramp and in avalon-dev, even after a hard refresh, so I think this is not yet fully solved. I haven't tested Chrome/Firefox yet.


[Private Zenhub Video](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMDFCQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--a78b758065efa3e186c528d09b0a4dfa07ad6d07/Screen%20Recording%202024-02-08%20at%2010.55.32%20AM.mov)

**Comment by masaball** [comment]
I just now did some quick testing on Safari and was only able to get it to trigger three times out of a couple dozen runs so it seems to be pretty flaky. In checking the other browsers, I sometimes get a single flicker but not the consistent flashing. My guess would be that this is another case of Safari dropping or ignoring an event. I will circle back to this and try get it fully working in Safari after I'm done on #394.

**Comment by masaball** [comment]
After more testing, this is not limited to Safari and is not flaky. I have a playlist item that still continuously flashes every time. I have not fully investigated but I think it may be that custom timespans are not being marked as `ended` properly? VideoJS sees the whole length of the duration, but the played duration does not match when we try to tell VJS that play has ended and maybe that is confusing VJS? Will continue to investigate and get a fix put together.

**Comment by elynema** [comment]
For testing purposes, we are also getting flashing when auto-play is turned off and the playlist item that was playing ends. This only happens if auto-play is turned off while the playlist item is playing.

**Comment by elynema** [comment]
I'm also seeing some weird flashing in Safari when using prev/next canvas buttons to advance through a playlist. The current playlist item flashes bold 1-3 times before the bold advances to the next playlist item. It is a little hard to tell if this is happening in Ramp, since the demo site reloads to the top of the page every time you click next canvas, and you have to scroll back down to see the playlist items, but I don't *think* it is happening in the demo site.

 This should be re-tested.


[Private Zenhub Video](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeGRRQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--08ce7c19f698f982e95ef88c9884aedd183faeaa/Screen%20Recording%202024-02-12%20at%206.10.19%20PM.mov)

**Comment by elynema** [comment]
Did a quick test in Ramp demo site on Safari and Chrome on macOS. I tested what happens when the last item in the playlist finishes, when the user advances to the next item using the next button, and when an item completes playback and auto-play is turned off (all cases noted above). I'm not seeing the crazy flashing. In each of these scenarios, the current playlist item flashes bold once in the list of items. This doesn't seem like a dealbreaker, so probably good to go ahead with this in the Ramp build as is?

**Comment by elynema** [comment]
@masaball  @joncameron  Tested this in macOS Safari in avalon-dev now that we have a new Ramp build. Overall, it is *much* improved. I am still seeing sometimes 1 and sometimes 3-4 blinks when clicking on an item in the playlist, as well as a blink when starting/stopping playback. Should I re-write this blinking as another issue? It's definitely odd and should be fixed at some point, but it doesn't really break anything.

[Private Zenhub Video](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBKzFjQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--47c1617d90c6393ce7e35d87c42bfbe98fb09059/Screen%20Recording%202024-02-14%20at%205.37.41%20PM.mov)


Here's a video:

**Comment by joncameron** [comment]
I'll create a new lower priority issue for removing all blinking behavior, but this issue can be closed since the primary case is handled here.
