### ISSUE TITLE
[BUG] 'scroll to see more' flashes repeatedly when scrolling to the end of a specific playlist in Chrome on Mac

### ISSUE THREAD

**Issue by elynema** [samvera-labs/ramp#372]
# Description

When you scroll to the bottom of a set of playlist items, the 'scroll to see more' / list of playlist items flash repeatedly. It looks like maybe the 'scroll to see more' text is flashing in and out and the text is adjusting around it, but I'm not sure.

Note: I have only been able to replicate this with one specific playlist: https://avalon-dev.dlib.indiana.edu/playlists/58. I added the same 3 playlist items at the end of this playlist to the end of another playlist, but the behavior did not recur.

This is happening in Chrome on Mac. This is not happening in Safari or Firefox.

[Private Zenhub Video](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeWNsQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--453adf52d622e76bef95670e13841b8e457f7be2/Screen%20Recording%202024-02-02%20at%2011.46.53%20AM.mov)

This is low priority since it only seems to be happening to one playlist, although could theoretically recur since don't know *why* it's happening.

**Comment by elynema** [comment]
Dananji and Jon C. are unable to reproduce.

**Comment by joncameron** [comment]
Needs to be retested and closed if appropriate.

**Comment by elynema** [comment]
No longer seeing this, so closing.
