### ISSUE TITLE
[BUG] Zoom scrubber issues with display of selected time when scrubbing on iPad and Android

### ISSUE THREAD

**Issue by elynema** [samvera-labs/ramp#383]
# Description

Although the overall functionality of the Zoom scrubber is working on both iPad and Android (remember, this feature does not come into play on iPhone), there are issues with the popup display of the current time you are clicking on. Presumably this feature is useful to help you with figuring out where you are in segment you are doing detailed scrub on.

On iPad, this problem had been reported previously. Now in Safari and Chrome, there simply is no indication of the current time you are clicking. Same behavior in Firefox on Android:

[Private Zenhub Video](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeHN1QXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--9d81cfc8853fb819ad68aea1bbea7a240e45ee9d/Screen%20Recording%202024-02-05%20at%206.44.01%20PM.mov)

On Chrome on Android, we see the problem that used to occur on iPad where the bubble with the timestamp of the first place you clicked in the Zoom scrubber persists.

[Private Zenhub Video](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeG91QXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--cff13e3c151846713794a961c4c928a3a31a9431/Screen%20Recording%202024-02-05%20at%206.37.02%20PM.mov)

**Comment by joncameron** [comment]
Time tooltip not working on mobile as it is in desktop devices. The behavior here in Chrome is a stray behavior.

This may be resolved on the volume control issue. On Chrome, a check was added for mobile and so this may be resolved via that. 

Needs to be retested on the Ramp demo site, or the next time a new Ramp build is on dev.

**Comment by elynema** [comment]
The display of currently selected time in zoom scrubber is a mouseover/hover, which does not have a complement on mobile devices. As with mediaelement.js behavior, Dananji has removed that functionality on mobile devices, including iPhone, iPad, and Android. So this was behaving as expected.

Re-tested now in Chrome on Android for the Ramp demo site, and it appears to have matching behavior now. I will move this to QA for a final last check once we have a new Ramp build.

**Comment by joncameron** [comment]
Tested in Avalon and working as expected.
