### ISSUE TITLE
[BUG] When adding a custom timespan and then the section that contains it, section starts playback at start of custom timespan

### ISSUE THREAD

**Issue by elynema** [samvera-labs/ramp#385]
# Description

In this scenario, add a custom timespan to a playlist. Then add the section that contains the custom timespan to the playlist immediately following (if there are tracks, do not create separate items for the tracks).

When you go to playback the playlist, the custom timespan plays correctly. However, when auto-play moves on to the next playlist item that represents the section that contains the custom timespan, playback begins at the same time that the custom timespan began. It's like the player is somehow accidentally remembering the start time of the custom timespan.

This only seems to happen when the custom timespan is part of the section that follows it in the playlist, so probably edge case??

This video attempts to demonstrate:

[Private Zenhub Video](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOTB1QXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--c87a9e6a28d7927dc520580cedd2e181d5ba9ac3/Screen%20Recording%202024-02-05%20at%2010.34.40%20PM.mov)

So far, only tested in Safari.

**Comment by joncameron** [comment]
Edge case but should be resolved later; should also test what happens when contiguous playlist items are different clips of the same section.

**Comment by joncameron** [comment]
I could not reproduce the buggy behavior in Safari using this playlist with multiple items from the same section (labeled Yellowstone). Will retest once it's in Avalon.

**Comment by elynema** [comment]
Note that I did test this in avalon-dev with 2 custom timespans in a row from the same section and did not have this issue.

**Comment by elynema** [comment]
@joncameron I replicated this on avalon-dev on Safari with this playlist: https://avalon-dev.dlib.indiana.edu/playlists/60 going from item #2 to item #3. Will need to be re-tested with the fix.

**Comment by elynema** [comment]
Tested with Ramp demo site in Safari and Chrome and problem is resolved.

**Comment by joncameron** [comment]
Tested in Avalon and confirmed resolved there as well.
