### ISSUE TITLE
Volume and Quality Selector Resets to Default On Each Canvas Change

### ISSUE THREAD

**Issue by joncameron** [samvera-labs/ramp#390]
# Description

**Comment by elynema** [comment]
@cjcolvar Apparently video quality selection is supposed to be remembered as well. Is that easy to add as part of this?

**Comment by cjcolvar** [comment]
:+1: I have both in my PR to ramp.

**Comment by elynema** [comment]
Testing: test this in both media item and playlist context

**Comment by elynema** [comment]
Tested on Ramp demo site in playlist and media item context in Safari and Chrome on macOS as well as Chrome on Android and Safari on iPad. Note that volume cannot be adjusted on mobile devices, so only quality selector is relevant there.

@cjcolvar @joncameron Volume is retained, but not mute. So if a user mutes the canvas, the next canvas is un-muted. Settings are also retained across records, not just canvases. If I load a new manifest into Ramp, it remembers volume level and quality selection from the last canvas.

**Comment by cjcolvar** [comment]
I'll take a look at mute.
The current approach of storing in localStorage thus making the setting sticky for a potentially really long time is the same as in Avalon 7.6/MCO.  I guess how long it stays around right now is dependent on when the browser clears out localStorage, but I guess we could try to tie it to session within Avalon and have localStorage get wiped on logout.

**Comment by elynema** [comment]
@joncameron @cjcolvar To be clear, I'm ok with the settings being sticky across records as long as localStorage lasts. I just wanted to note that was happening in case anyone else had an issue with it. Given that if the user changes volume, the new level is sticky, I really don't see it being an issue.

**Comment by elynema** [comment]
@cjcolvar Looks like mute is not being retained when switching from a video to an audio canvas on Chrome on Android or Safari on iPhone. Quality level is being retained.

Safari and Chrome on macOS handled the mute fine.

**Comment by joncameron** [comment]
@cjcolvar Can you take a quick look and see if the mobile issue is a potentially easy fix? Otherwise I'll close this issue and create a bug ticket just for the Android and iOS behavior.
