### ISSUE TITLE
[BUG] Inaccessible items do not show error message and do not display title below media player

### ISSUE THREAD

**Issue by elynema** [samvera-labs/ramp#394]
# Description

Seems to be a regression problem with inaccessible items.

- If I pull up a playlist with inaccessible items
- Click on one of the inaccessible items
- No error message shows up in the media player space. Should say "You do not have permission to playback this item"
- Title of inaccessible playlist item does not show up below the media player space

<img width="1210" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMW84QXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--bb44470bfc1c8bc8d4f4afad21e0b114df4acb95/image.png" alt="image.png" />

Auto-play seems to be moving through inaccessible items every 10 seconds as expected.

# Done Looks Like

- [x] Should display message "You do not have permission to playback this item" when a user clicks on an inaccessible item or auto-play reaches an inaccessible item
- [x] Title / description of inaccessible item should display just under the media player space, just like for all other playlist items

**Comment by elynema** [comment]
This seems to be working again?

**Comment by elynema** [comment]
@charumitraravi To test on Ramp demo site. See playlist https://avalon-dev.dlib.indiana.edu/playlists/33/manifest.json in Ramp demo site.

**Comment by elynema** [comment]
To test on avalon-dev: https://avalon-dev.dlib.indiana.edu/playlists/33

**Comment by elynema** [comment]
@masaball Tested in Safari on macOS. The error message is showing properly to users, but the title of the inaccessible item is not populating below the media player area.

<img width="1091" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBK3RjQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--63fb2f4f84d33c4d3e1f26e746839e451821a7ee/image.png" alt="image.png" />

**Comment by masaball** [comment]
It looks like it is not loading properly on all browsers. I'm seeing an error in the console related to running a function on an undefined item and checking the element inspector the hidden dummy player is not being generated. So I think an unrelated feature change broke the dummy player generation for blank canvases.

**Comment by elynema** [comment]
@charumitraravi Can you re-test this on the Ramp demo site to verify the title of the inaccessible item is populating below the player as it should?

**Comment by joncameron** [comment]
This is showing as expected for me in avalon-dev and seemed good on the Ramp demo site as well.
