### ISSUE TITLE
[BUG] Default element size on Android Samsung devices renders full screen button off screen and inaccessible

### ISSUE THREAD

**Issue by elynema** [samvera-labs/ramp#402]
# Description

Android Samsung devices seem to have a larger element size than Google Pixel devices. This causes the icons in Ramp to render larger, which forces the full-screen button off screen on these devices. It is inaccessible and the user cannot scroll to access it.

This was tested in Chrome and Firefox on Galaxy s23 v. 13.

<img width="363" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNXBJQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--e606414ffe312ef8649b4c6d6043458c06c01ac5/bs_realdroid_Mobile_Samsung%20Galaxy%20S23-13.0-1080x2340%20%282%29.jpg" alt="bs_realdroid_Mobile_Samsung Galaxy S23-13.0-1080x2340 (2).jpg" />

Ideally, we could re-size these elements so that they fit on at least both of these popular device categories.

**Comment by joncameron** [comment]
Could be done on the Avalon side. Need to test the Ramp demo site with the same device to see if the problem appears there. If this is coming from Avalon styling, recreate the issue in the Avalon repo.

**Comment by elynema** [comment]
It looks like I am seeing something similar on iPad in Safari. This is likely because the Safari browser on iPad uses Ramp player in fullscreen, just like Android does?

<img width="525" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBd1ZRQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--94097f70a6d5ec082c304dde3d531e0c3afd65c7/image.png" alt="image.png" />

**Comment by elynema** [comment]
Note that it sounds like Samsung is probably the most popular of Android devices. We are seeing Chrome on Android as the #3 most common OS/browser combination in accessing MCO.

**Comment by Dananji** [comment]
The icons show up as expected in the Ramp demo site on this device. So the fix was put on the avalon side as a CSS rule to reduce the size of the icons in the player's control bar.

**Comment by joncameron** [comment]
@Dananji On dev I don't see the full screen icon except in landscape mode:
<img width="367" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeG1mQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--4ec94bcf7f9db356ff84c3fc6b9f64f4513e442e/Screenshot%202024-02-29%20at%2010.27.13%E2%80%AFAM.png" alt="Screenshot 2024-02-29 at 10.27.13 AM.png" />

Could this be tweaked so the icon still appears in the control bar in portrait? Or is it a situation where we need to remove another of the icons for space reasons?

**Comment by elynema** [comment]
@charumitraravi Can you check in today and see how the full screen icon is showing in portrait for Samsung devices when the media item has a duration longer than an hour? This should be testable on avalon-dev and in the Ramp demo site.

**Comment by charumitraravi** [comment]
Tested on multiple samsung and pixel devices (real device and on browser stack). Latest versions of pixels seem fine. Although , I did find the icon getting slightly hidden on older smaller devices like samsung A34 (on browser stack)
