### ISSUE TITLE
[BUG] Player controls not responding to mouse-over for playlist item videos; volume control not working in Safari (macOS)

### ISSUE THREAD

**Issue by elynema** [samvera-labs/ramp#410]
# Description

On the playlist page, the player controls are not responding to mouse-over in Safari on macOS.  This seems to be happening to videos, but not to the audio playlist item I tested.

- When hovering over the player icons, no tooltips pop up. Once the toolbar in the media player disappears, hovering over the player does not bring it back up. The user has to click on the video to make it reappear.
- The volume adjustment does not work because the slider is not toggled on mouse-over. The user can only mute/un-mute. If the user clicks the volume icon once, it will mute and then raise the slider, which can then be adjusted (and stays visible controls disappear)
- The quality control menu only toggles on click, not on mouse-over.
- The closed captions also require click to expand options, rather than on mouse-over.

I did not see any errors in the Javascript console.

Note that these errors are not occurring in playback on the media item page, just the playlist page.

[Private Zenhub Video](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOE5RQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--8951dd86280f8ac57f115fb8c6b4744064595564/Screen%20Recording%202024-02-12%20at%2010.32.33%20PM.mov)

**Comment by joncameron** [comment]
Closing; may have been a result of an environment issue.
