### ISSUE TITLE
[BUG] Currently active item in structured nav blinks during certain transitions

### ISSUE THREAD

**Issue by elynema** [samvera-labs/ramp#420]
# Description

Under certain circumstances, the title of the selected playlist item in the structured navigation will blink between 1 and 4 times. This happens:

Playlist context:
- when clicking on an item in the playlist 
- when using the next button to advance to the next canvas
- when starting/stopping playback of an item in a playlist
- when the last item in a playlist finishes

Media item page context:
- when clicking on a timespan in the structured nav on a media item
- when starting/stopping playback of a timespan in the structured nav
- when using the prev/next button to advance to a timespan in the structured nav (ex: navigating to a section that begins with a timespan highlighted)

This video shows some examples:

[Private Zenhub Video](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNnRpQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--06a6597476fa7eeb981959982309eb635702994e/Screen%20Recording%202024-02-14%20at%205.37.41%20PM.mov)

On the item page:
![Feb-28-2024 14-57-28](https://github.com/samvera-labs/ramp/assets/1406618/baf68cf2-b4f9-40d5-99be-7355b74a953c)

See past history on https://github.com/samvera-labs/ramp/issues/370.

**Comment by joncameron** [comment]
Could be due to state updates happening multiple times quickly.

**Comment by elynema** [comment]
@charumitraravi I can't assign this one to you b/c you're not in the Ramp repository, but can you take a look at this one? The ticket description lists the times that we were seeing blinking in the navigation as a checklist to run through.

**Comment by charumitraravi** [comment]
Tested both the playlist and the media object page. Although the blinking issue has been resolved in the context of the structured nav item, the entire page seems to flicker now. Tested the same scenario on Avalon staging, and I was unable to replicate the page flicker. 


Page flicker on media object page

https://github.com/samvera-labs/ramp/assets/52535309/00b8e751-8d83-460c-8016-8ae5806f1df1

**Comment by joncameron** [comment]
Created samvera-labs/ramp#462 for the broader flickering issue.
