### ISSUE TITLE
Very Large Font Size for Native Player Captions in iPad Chrome

### ISSUE THREAD

**Issue by joncameron** [samvera-labs/ramp#423]
# Description
In Chrome on an iPad, the native caption font size is very large: 
<img width="559" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeHRvQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--b068d482693f6e653f680b6ca4d755380e4ec355/bs_realios_Tablet_iPad%20Pro%2012.9%202021-17.0%20%282%29.jpg" alt="bs_realios_Tablet_iPad Pro 12.9 2021-17.0 (2).jpg" />

This is only when captions are turned on in the native player, which happens in Chrome rather than Safari, so this is an edge case bug.

# Done Looks Like
- [ ]

**Comment by elynema** [comment]
Need to re-test; this is probably resolved with 7.8 code.

**Comment by elynema** [comment]
Closed as resolved with video.js upgrade, see Ramp #526.
