### ISSUE TITLE
Selecting unplayable audio format disappears format selection widget

### ISSUE THREAD

**Issue by triplingual** [samvera-labs/ramp#434]
**Bug Description**
Format choice widget disappears for audio if an unplayable format is chosen.

**To Reproduce**
1. Go to [the IIIF Cookbook's AV Choice recipe preview](https://preview.iiif.io/cookbook/0434-choice-av/recipe/0434-choice-av/)
2. Scroll down to the **Example** section
3. Click on *View in Ramp*
4. In the Ramp public demo page that opens, click on the gear icon on the righthand side of the player
5. In the format selection widget, choose `mpeg2`

**Expected behavior**
Though I don't have specific behavior I expect from Ramp, I would say generally speaking that I would expect to get the message that the file cannot be played, while keeping the format selector widget so I could play a different format

**Screenshots**
![Initial view of format selection widget](https://github.com/samvera-labs/ramp/assets/1789625/0c02af32-8bca-4d80-8b9f-7f4ea0f57937)
*Initial view of format selection widget*

![Format selection widget clicked](https://github.com/samvera-labs/ramp/assets/1789625/a7793d1c-e2f9-4390-8c7a-131fdb53137f)
*Format selection widget clicked*

![`mpeg2` option clicked](https://github.com/samvera-labs/ramp/assets/1789625/761b8bf5-31cf-4889-bb0a-791089993f4e)
*`mpeg2` option clicked*

![Player bar showing error message and absent format selection widget](https://github.com/samvera-labs/ramp/assets/1789625/8cada86c-5f1f-45d9-99b6-8121ade798e8)
*Player bar showing error message and absent format selection widget*

**Desktop (please complete the following information):**
 - MacOS 14.1.2
 - Firefox
 - 115.8.0esr

**Additional context**
+ If the cookbook recipe preview has gone away, the final version should eventually be at [https://iiif.io/cookbook/0434-choice-av/recipe/0434-choice-av/](https://iiif.io/cookbook/0434-choice-av/recipe/0434-choice-av/)
+ After reaching the one-way dead end street once, I find that I have to clear my browser cache before I can get the format selection widget to return.

**Comment by joncameron** [comment]
2 issues:
- control panel is unavailable when the player hits a stream it can't read
- the mpeg2 file should load and play

**Comment by joncameron** [comment]
Quality selector in Video.js handles the source change and this is outside of Ramp; will need to investigate to see what the cause of the error is.

**Comment by joncameron** [comment]
This looks good for the error: the error message is readable, dismiss-able and much more clear to users. I'll create a new issue for the issue of the mpeg file from the IIIF cookbook example not playing.
