### ISSUE TITLE
Support .srt formats for transcripts

### ISSUE THREAD

**Issue by elynema** [samvera-labs/ramp#441]
**Is your feature request related to a problem? Please describe.**
Currently, Ramp only supports .vtt, plain text, and .docx formats for transcripts. Many caption files that are produced as .srt could be appropriate for transcripts, as well.

**Describe the solution you'd like**
Parse .srt format files provided to the transcript component and display them as interactive timed text.

**Additional context**
One motivating factor for considering this is that the .vtt files produced by auto-generated captions in Youtube seem to be invalid, and so don't work for transcripts in Ramp. However, the .srt files seem to be valid and could be an alternate option. It's unclear whether this is just a Youtube issue, or whether we might run into other issues with .vtt files produced by external systems?

An alternative to this is manually fixing .vtt files downloaded from Youtube, which is easy to do, as it requires deleting several lines at the start of the file.

Note that if we end up treating captions as transcripts in Avalon for search/display purposes, then we'll need to reconcile the format we allow as captions and transcripts; this could be another reason to support .srt for transcripts.

[youtube-webvtt-example.vtt.txt](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMzZmQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--2473b2bc315e832e1e128c376c01acd511396e3b/youtube-webvtt-example.vtt.txt)

[youtube-srt-example.srt.txt](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNENmQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--be981d61105e0dc050d43293f88e7dca20aa4dec/youtube-srt-example.srt.txt)

**Comment by joncameron** [comment]
Works great, example used for testing at https://avalon-dev.dlib.indiana.edu/media_objects/8s45q877v.
