### ISSUE TITLE
[BUG] All captions are highlighted as selected

### ISSUE THREAD

**Issue by Dananji** [samvera-labs/ramp#452]
### Description

In the captions menu in Ramp, all captions are shown as selected even though only one caption is selected.
![Screenshot 2024-03-14 at 4 43 50 PM](https://github.com/samvera-labs/ramp/assets/1331659/3361d8b4-24e8-4477-ad6c-ca2688e38613)

### Environment
- All desktop browsers (Safari, Firefox, Chrome)
- Chrome and Safari in iPad
- Chrome in Android

### Done Looks Like

- [ ] Only the selected caption is shown as selected on player initialization

### Notes
Ramp only sets `default` attribute to `true` for the first caption in the list, but Video.js makes 2 passes over the text tracks list and marks multiple captions as selected in the captions menu when initializing.

**Comment by elynema** [comment]
Test on demo site before we make a new Ramp PR.

**Comment by charumitraravi** [comment]
Verified this item on the Ramp demo site on Chrome and Safari browsers, on web and mobile. The fix is working as expected.
