### ISSUE TITLE
Nonfunctional "CC" Option Appears in iOS Native Player

### ISSUE THREAD

**Issue by joncameron** [samvera-labs/ramp#472]
# Description
When one or more caption/subtitle files are available, the iOS native player displays a "CC" option in the list of available tracks. Selecting this CC track does not display any of the captions. Why is this populating here? 

# Screen Capture
<img width="390" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeW8yQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--a3416e546faef75cf817d7724447fea0cfd48c58/Screenshot%202024-04-04%20at%2011.34.52%E2%80%AFAM.png" alt="Screenshot 2024-04-04 at 11.34.52 AM.png" />

# Environment
iOS 16 on iPhone 14, Browserstack

# Done Looks Like
- [ ] "CC" does not appear in the Subtitles menu in the iOS native player

**Comment by Dananji** [comment]
I think this is an iOS bug: https://github.com/videojs/video.js/issues/2808

We remove this redundant `CC` option in the Video.js interface in [Ramp code](https://github.com/samvera-labs/ramp/blob/main/src/components/MediaPlayer/VideoJS/VideoJSPlayer.js#L279-L293) in the iOS context.
I don't know whether we can remove the `CC` option in the native iOS player in the captions menu.

**Comment by joncameron** [comment]
For right now this seems like a known issue that can be recorded; captions menu in the native iOS player is completely separate and we don't have control there except in some instances (like providing known caption tracks).

**Comment by elynema** [comment]
Close this and add to known issues.

**Comment by elynema** [comment]
Already listed as a bug here: https://samvera.atlassian.net/wiki/spaces/AVALON/pages/1957954635/Bugs+and+Known+Issues
