### ISSUE TITLE
Long metadata values cause horizontal scrollbars

### ISSUE THREAD

**Issue by cjcolvar** [samvera-labs/ramp#486]
**Describe the bug**
Long metadata values in the manifest can overflow the visible space for the Details tab causing horizontal scroll bars.  Can probably be solved with `word-break` and/or `word-wrap` CSS properties.

Example: https://avalon-dev.dlib.indiana.edu/media_objects/x920fw86z

**Expected behavior**
Long metadata values wrap so there isn't any overflow and no horizontal scroll bars.

**Screenshots**
![image](https://github.com/samvera-labs/ramp/assets/1053603/78493067-0fe6-4141-b452-4121c40585c5)

**Comment by joncameron** [comment]
Will need to test in Avalon after this is changed in Ramp since there is extra styling applied there.

**Comment by joncameron** [comment]
Lines are wrapping as expected now.
