### ISSUE TITLE
Selecting SRT transcript on demo page crashes browser tab

### ISSUE THREAD

**Issue by patrick-lienau** [samvera-labs/ramp#489]
**Describe the bug**
Looks the the SRT transcript for the demo page is being parsed incorrectly resulting in a hung page. This appears to be a regression beginning in [9f24f0e](https://github.com/samvera-labs/ramp/commit/9f24f0e9f8f049601e4d0c24753eb950572c62ff) which fixed #476.

**To Reproduce**
1. Go to https://iiif-react-media-player.netlify.app/
2. Click on the Transcript tab and from the dropdown choose "SRT Transcript"
    ![image](https://github.com/samvera-labs/ramp/assets/115490089/e390563a-94b6-41a5-b5ac-505bdb3dc412)
3. Browser window becomes unresponsive.

**Expected behavior**
For the browser to not be bricked, even if there was an error.

**Screenshots**
![image](https://github.com/samvera-labs/ramp/assets/115490089/0530ab76-0a5d-4ed2-88a9-f539f6662983)

This is not some browser bug. I've tested Chrome, Firefox, and Safari on my MBP. I'm confident you'd get similar behavior on any platform. The issue is present on your live demo site as well as locally after running `yarn demo` on the most recent commit ([56c0bc4](https://github.com/samvera-labs/ramp/commit/56c0bc417842baf8bd4e748cd1d0ec480447970e)) to the `main` branch.

**Additional context**
Before using the transcript dropdown the following error can be observed in DevTools:
```
Text Track parsing errors for https://iiif-react-media-player.netlify.app/lunchroom_manners/lunchroom_manners.srt
video.es.js:222

VIDEOJS: ERROR: a
  code: 0
  message: "Malformed WebVTT signature."
  name: "ParsingError"
    [[Prototype]]: Error
      constructor: ƒ a(e,t)
      [[Prototype]]: Object
      
(anonymous) @ video.es.js:222
```

Setting a breakpoint on `video.es.js:222` allowed me to inspect a more meaningful error a few stack frames up:
![image](https://github.com/samvera-labs/ramp/assets/115490089/55684f10-2eb9-4469-bf13-15f93437f6a3)

## QA Notes from Charu about SRT crashing: (see https://github.com/samvera-labs/ramp/issues/467#issuecomment-2116393279)
1. When I try to access an item that only has an SRT transcript (for example, [this page](https://avalon-dev.dlib.indiana.edu/media_objects/4x51hj01t)), the webpage crashes.

2. If a media item has multiple transcripts available and one of them is an SRT file, the page also crashes when I select the SRT transcript from the list (as seen in [this example](https://avalon-dev.dlib.indiana.edu/media_objects/g158bh28p)).
(refer the screenshots attached)

<img width="1086" alt="Screenshot 2024-05-16 at 7 45 08 PM" src="https://github.com/samvera-labs/ramp/assets/52535309/ca5d23f9-5f33-475c-ba91-2bfb22b797d3">
<img width="856" alt="Screenshot 2024-05-16 at 7 47 59 PM" src="https://github.com/samvera-labs/ramp/assets/52535309/6a94a648-3009-440c-9e22-f05478a6bf8e">

**Comment by joncameron** [comment]
No longer crashing upon selection of SRT file in the Transcript component.
