### ISSUE TITLE
Change Playlist Description Label

### ISSUE THREAD

**Issue by joncameron** [samvera-labs/ramp#498]
## Description
Ramp currently shows the description of a playlist as "Comment"; this should be changed to "Description" to match the descriptive metadata property and the text that appears elsewhere in the application.

The Description field for Playlists should also respect newlines. Currently when Ramp renders the description text newlines are stripped.

## Current
![Screenshot 2024-05-21 at 10 33 26 AM](https://github.com/samvera-labs/ramp/assets/1406618/10339a3c-f00f-4b84-b262-2cb246d89fa8)

## Expected
![Screenshot 2024-05-21 at 10 34 21 AM](https://github.com/samvera-labs/ramp/assets/1406618/c01706b8-b044-4276-bf78-74853aafd672)

## Playlist Edit Page - Description With Newlines
![Screenshot 2024-05-23 at 1 44 06 PM](https://github.com/samvera-labs/ramp/assets/1406618/ea54fc50-a12f-430f-aa0c-8b1e0199e828)

## Playlist View Page - Description Has Newlines Stripped
![Screenshot 2024-05-23 at 1 44 15 PM](https://github.com/samvera-labs/ramp/assets/1406618/83d7fcec-6c8d-45da-a231-0e5d30b4e220)

## Playlist View Page - Expected
![Screenshot 2024-05-23 at 1 47 52 PM](https://github.com/samvera-labs/ramp/assets/1406618/4a843411-b5b5-4d30-bf94-d9cf4dccf831)

## Done Looks Like
- [x] "Comments" changed to "Description" for playlists 
- [x] Description text is rendered with newline characters

**Comment by elynema** [comment]
@joncameron Misti asked if the size of this field could be expanded as large as possible, also. Could we include that in this issue or do we need a separate ticket?

**Comment by joncameron** [comment]
I created https://github.com/avalonmediasystem/avalon/issues/5839 for expanding the size of the playlist description since that's a database field in Avalon. I also edited this ticket to include handling of newlines in the description text which I found wasn't rendering as expected while testing.

**Comment by joncameron** [comment]
Test playlist: https://avalon-dev.dlib.indiana.edu/playlists/98
