### ISSUE TITLE
Transcript component parses 'note' within cue-text as plain text

### ISSUE THREAD

**Issue by Dananji** [samvera-labs/ramp#499]
### Description

Transcript component parses the `NOTE` block in a WebVTT file as plain text and displays in the component. The parse is set to identify these blocks in the header as well as in between the cues in the file.
When there's `note` text within the cue's text with a line break in front of it, the parser recognizes it as a `NOTE` block in the WebVTT file instead of as part of the cue.

### To Reproduce
1. Go to https://avalon-dev.dlib.indiana.edu/media_objects/gf06g267d/
2. Click on second section named 'The Legislative Organization of Congress'
3. Select 'Transcripts` tab
4. Scroll down to transcript cue with the timestamp `00:24:21`
5. See the text for that cue is broken into 2 lines, where the text 'note that neither the Majority' is not a clickable transcript cue, but a plain text display

### Expected behavior
Whole cue text:
- [ ] needs to be contained within a single `<span>` element
- [ ] needs to be linked (clickable) and highlighted when user interacts with the cue
- [ ] is highlighted when playback reaches the respective timestamp

### Screenshots
Example cue;
```
00:24:21.400 --> 00:24:24.370 align:middle line:84%
It's interesting to me to
note that neither the Majority
```
This is displayed in the Transcript component as follows;
![Screenshot 2024-05-14 at 1 22 07 PM](https://github.com/samvera-labs/ramp/assets/1331659/31a74c34-89bf-42a2-9844-2e9513518584)

### Additional context
Related previous work: #440

**Comment by joncameron** [comment]
May need to change intermediate parsing so that "note" at the beginning of a line doesn't get parsed like this. Note blocks in VTT don't have special characters to disambiguate, but there are strategies to work around this, like better handling of line breaks.
