### ISSUE TITLE
Bring IIIF Content Search into Transcript Component

### ISSUE THREAD

**Issue by joncameron** [samvera-labs/ramp#502]
## Description
Intermediate functionality is needed to convert our Content Search API-based search responses to the format implemented by Third Wave in the Transcript component. For this issue, transcript component architecture isn't as important since the bulk of this work will be on parsing. Discussion of transcript component architecture can come after this work.

## Done Looks Like
- [x] Parse the search service in the manifest 
- [x] Pass search service into the search as a Matcher Factory when search functionality is called
- [x] Convert IIIF content search response into format that can be parsed by the search within component
- [x] Transcript search returns search results for all existing transcripts for current canvas.
- [x]  Drop-down to select transcript shows # of hits in each transcript (like Aviary)
- [x]  Searches submitted from the transcript search box on a media item should be submitted as phrase searches and only produce phrase matches in the transcript(s).

**Comment by joncameron** [comment]
## Description
The way search is written, we may need intermediate functionality to convert search responses to the format implemented by Third Wave in the Transcript component.

There are 2 ways to use the API: to use the props, and to pass the search service in the parser and pass that on. We probably would go with the latter (parsing), and we'll need a ticket to parse the search service in the manifest and pass that into the search as a Matcher Factory to call it when searching is happening in the UI.

**Comment by joncameron** [comment]
Other thing: does the Transcript component need to be independent still? If so, we may need to change code; Patrick has pulled the component under the overall state which will complicate standalone usage. We should have a discussion on this: what are our needs? Do we need to keep it any particular way?

**Comment by joncameron** [comment]
See samvera-labs/ramp#502 for discussion of retaining independence for the Transcript component.

**Comment by elynema** [comment]
@Dananji I'm seeing an issue with this example record: https://avalon-dev.dlib.indiana.edu/media_objects/gf06g267d. I don't know if it's related to re-formatting the IIIF content search or if it's related to displaying search results.

For the first section, if I go to the transcript tab and search 'Isaac' I get no results, even though Isaac is clearly in the first few lines of the transcript. The underlying IIIF content search is providing a result, but it's not getting shown in the front-end.

**Comment by elynema** [comment]
Same issue when I search 'depaul' or 'university' in this transcript. Hits are not being shown in the interface. I am not seeing this issue in other sections on this record so not sure if it is related to the transcript or section in particular.

**Comment by elynema** [comment]
In addition, if I submit a search, and then select a new section, the search carries over. This would be fine if the search re-sets itself to the new transcript, but it seems to retain the number of hits from the previous transcript, and it is also carrying over the cue with the active hit from the prior transcript and displaying it at the top of the new section's transcript.

<img width="1402" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBd2FWQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--b3d451fb19e0fb8372795125135d529a52bf642f/image.png" alt="image.png" />

**Comment by elynema** [comment]
Basic issues reported here are resolved across Safari, Chrome, Android, iOS. Closing this and opening some new issues.
