### ISSUE TITLE
Typeahead for Transcript Search

### ISSUE THREAD

**Issue by joncameron** [samvera-labs/ramp#509]
## Description
Transcript search queries are being made for every character entered into the search field; will this create any problem with a slower response from the Content Search API? Or should there just be a delay until the final key press event to send the query? We can use the existing style found on the collection index for this style of search.

## Done Looks Like
- [x] Test performance when using Content Search responses upon each keypress in the transcript search component
- [x] Check to make sure we don't need to implement the IIIF autocomplete service as part of this

**Comment by elynema** [comment]
This is working fine in avalon-dev.
