### ISSUE TITLE
Scrubbing doesn't work in native player on demo site

### ISSUE THREAD

**Issue by elynema** [samvera-labs/ramp#516]
## Description

When testing the demo site in the iOS native player, scrubbing using the progress bar and the forward / backward 10 seconds buttons is not working at all. When the progress bar is dragged, the bar moves, but the video doesn't actually advance. When you click the forward / backward 10 seconds buttons, nothing happens to the video; it just continues playing.

I tested this in iPhone in Browserstack iOS 17 on the Ramp demo site, as well as iOS 16 on my local device. Scrubbing in the native player is working on mco-staging and on avalon-dev, so this must have been recently introduced in a Ramp change. 

Could this be related to fixes for the slow scrubbing in #494?

### Example from iOS 17 on Ramp demo site
![Jun-11-2024 10-14-03](https://github.com/samvera-labs/ramp/assets/1406618/add992cf-6468-4e76-a20e-35b199fa43e7)

## Done Looks Like
- [ ] Seeking and scrubbing is functional in iOS the native player

**Comment by joncameron** [comment]
Odd rendering of VTT as well—text is left-aligned with an unexpected background color. Is this related to the same problem? If not we can create a new ticket to fix.

**Comment by elynema** [comment]
Scrubbing does now seem to be working in the native player on the demo site. It is no longer working on avalon-dev, so leaving this here to finish QA once this Ramp build is pulled into Avalon.

**Comment by elynema** [comment]
@charumitraravi Can you QA this?

**Comment by charumitraravi** [comment]
QA completed. Scrubber is working as expected on the native player
