### ISSUE TITLE
Next canvas button does nothing on playlist page after page load

### ISSUE THREAD

**Issue by elynema** [samvera-labs/ramp#523]
# Description

In the playlist context, the next canvas button does not do anything if selected immediately after page loads while on the first playlist item. This is true whether you start the first playlist item playing or not. If you select or play through to another playlist item, the next / previous canvas buttons seem to work fine. 

This was tested in Safari on desktop in avalon-dev.

Example playlist: https://avalon-dev.dlib.indiana.edu/playlists/75

This issue does not seem to be happening on the media object page.

# Done Looks Like

- [ ] Next canvas button should load the next playlist item into the player

Note: this happened repeatedly to me, but then stopped happening for the same playlist, so holding this here to see if the problem recurs

**Comment by joncameron** [comment]
I tested but couldn't reproduce in desktop Safari. Maybe fixed in another change in the latest Ramp build?

**Comment by elynema** [comment]
This is probably a duplicate of some of the issues reported in Ramp #548, so closing as that lists specific examples to re-create.
