### ISSUE TITLE
Progress bar overlaps other buttons in media player on iPhone on initial load

### ISSUE THREAD

**Issue by elynema** [samvera-labs/ramp#524]
**Describe the bug**
With the addition of the playback speed widget, the buttons in the bottom bar of the media player are no longer fully accessible on iPhone. On Android Samsung devices, we see this same overlap while the player is loading in Ramp but once the media item can be played, the progress bar re-sizes to work properly.

**To Reproduce**
1. iPhone iOS 17 in Browserstack
2. Load a media item page in Safari. Example: https://avalon-dev.dlib.indiana.edu/media_objects/g158bh28p
3. on iPhone, the progress bar overlaps the time and the zoom scrubber button
4. When playback begins, the native player opens. If you exit full screen, the buttons show up ok in the media player in browser, so apparently the problem only happens when the media player is first rendered.

**Expected behavior**
the progress bar should be re-sized to available space in the media player when the page first loads.

**Screenshots**
<img width="369" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBN1JpQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--a12c40e7162aadb9d4f3f055026c51a5a9147707/screenshot-iPhone%2015-17.0.png" alt="screenshot-iPhone 15-17.0.png" />

**Smartphone (please complete the following information):**
 - Device: iPhone
 - OS: iOS 17
 - Browser:Safari
 - 
**Additional context**
As this issue looks bad, but is mostly non-breaking due to use of native player once video playback starts, it may not be required for 7.8. release in Avalon.

**Comment by elynema** [comment]
Could be an event that is supposed to fire on initial load is not firing properly.

**Comment by Dananji** [comment]
I was not able to reproduce this on Browserstack iPhone 15 on iOS 17.5.

**Comment by elynema** [comment]
@Dananji I was able to reproduce this in Browserstack iPhone 15 on iOS 17.5 I did not see it in iOS 17 in the same environment. What record did you use? I used the one linked in this issue.

<img width="369" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNU1zQmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--30de82fc1b219fb54b78f47be810f11493767870/screenshot-iPhone%2015-17.5%20%284%29.png" alt="screenshot-iPhone 15-17.5 (4).png" />

**Comment by Dananji** [comment]
I used the same item. I re-tested in both iOS 17 and 17.5 on iPhone 15 and was unable to reproduce this.

**Comment by elynema** [comment]
@joncameron would you be willing to test this one out, too.

**Comment by joncameron** [comment]
I tested on my iPhone 13 with iOS 17.5 and in Browserstack with iPhone 15 and iOS 17.5 and couldn't reproduce.

**Comment by elynema** [comment]
Since we have 2 other folks who cannot reproduce, I'm going to mark this as closed.
