### ISSUE TITLE
Can't access full-screen button in Android Samsung devices

### ISSUE THREAD

**Issue by elynema** [samvera-labs/ramp#525]
**Describe the bug**
On Android Samsung devices, the full-screen button is missing from the right corner of the media player. (BrowserStack won't allow me to rotate this device for some reason, so I can't confirm if it is actually missing or just doesn't have enough space).

**To Reproduce**
1. Go to Android Samsung Galaxy device (v14 OS) in Browserstack
2. Open a media object in chrome. Example: https://avalon-dev.dlib.indiana.edu/media_objects/g158bh28p
3. There is no full-screen button in the bottom right of the media player.

**Expected behavior**
The full-screen button should show in the far right of the media player on Android Samsung devices.

**Screenshots**
<img width="369" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBN1ZpQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--04b069f47fffec59b6b38bfbaf627078a8ee5d07/screenshot-Samsung%20Galaxy%20S24-14.0.png" alt="screenshot-Samsung Galaxy S24-14.0.png" />

**Smartphone (please complete the following information):**
 - Device: Samsun Galaxy S24
 - OS: 14
 - Browser Chrome

**Additional context**
This problem is not happening in Google Pixel devices.

**Comment by elynema** [comment]
This looks ok on the demo site, but needs to be tested in the avalon context to finish QA.

**Comment by elynema** [comment]
@charumitraravi Can you QA this one?

**Comment by charumitraravi** [comment]
If I increase the display size the full screen button still gets hidden (This is on samsung s23 ultra, which is more wider than most devices.)
(Image 1 - increased by 2 units from default , image 2 - increased 1 unit from default size)
Although , this could just be an edge case , considering users who prefer bigger display of elements / smaller devices


![samsung2](https://github.com/samvera-labs/ramp/assets/52535309/3bec080c-aa52-4177-a18e-c0a902a7990d)


![samsumg1](https://github.com/samvera-labs/ramp/assets/52535309/21fc0677-e2d5-4eb8-82f6-886964948c82)

**Comment by elynema** [comment]
@Dananji Do we have any options for resolving this? I know we are supposed to support up to 200% zoom.

**Comment by Dananji** [comment]
@elynema, @charumitraravi I tested on a Samsung Galaxy S24 v14.0 device in BrowserStack, by using zoom in 2 different ways and I was not seeing what's captured in the screenshots above.

1. By setting the zoom to 200% in the browser and this is what I was seeing;

![bs_realdroid_Mobile_Samsung Galaxy S24-14 0-1080x2340](https://github.com/samvera-labs/ramp/assets/1331659/1c0c12ab-de7c-43de-9cb4-9a495d1294fe)

The way I used zoom: Browser settings (click vertical dots on the top right hand side corner) -> Accessibility -> Drag the text scaling slider to 200%.

2. Pinch and zoom which enlarges the entire page which is equivalent to an image zoom.

And I tested these on `avalon-dev` not on `avalon-staging`, because this fix is not in staging yet.

Could you please clarify the steps you followed as well?

**Comment by elynema** [comment]
I also tested with Galaxy s23 ultra in Browserstack. I increased text zoom to 200% in the browser's Accessibility menu and did not replicate this issue.

![screenshot-Samsung Galaxy S23 Ultra-13 0](https://github.com/samvera-labs/ramp/assets/109625239/2e17a8ea-adc9-4366-8027-fb7a8bc112a0)

**Comment by charumitraravi** [comment]
@elynema 
I adjusted the display size from the phone settings, and not the browser zoom. It is used to set the overall display size of all the elements, and not just the browser.

**Comment by Dananji** [comment]
@charumitraravi Could you please mention the steps to change the display size? I see there are multiple ways in the Accessibility settings to change the size.

**Comment by Dananji** [comment]
I bumped the 'Font size and style' and 'Screen Zoom' all the way up in the phone's Accessibility settings and I got the following, which has the fullscreen button partially visible:

![screenshot-Samsung Galaxy S23 Ultra-13 0](https://github.com/samvera-labs/ramp/assets/1331659/792c53d3-f8f5-4e72-9733-3e40508046c0)

**Comment by charumitraravi** [comment]
@Dananji Its the screen zoon under settings-> display-> screenzoom. I believe it varies with devices, and thus an edge case

**Comment by Dananji** [comment]
No both of these were under Settings -> Accessibility settings -> Visibility enhancements

**Comment by Dananji** [comment]
@charumitraravi I tested with the settings change you mentioned (bumped Screen zoom all the way up) and I got the same partial visibility of the fullscreen button as above.
The device I tested is Samsung Galaxy S23 Ultra in Browserstack.

**Comment by joncameron** [comment]
@joncameron Check the behavior and see if known issue or not

**Comment by joncameron** [comment]
I think this is edge case enough to fall under this existing issue/known issue: https://github.com/avalonmediasystem/avalon/issues/5410. Closing this one.
