### ISSUE TITLE
Large caption text display on Android devices in fullscreen

### ISSUE THREAD

**Issue by elynema** [samvera-labs/ramp#526]
# Description

We are seeing large caption text display on Android devices again. This was a problem that was resolved in 7.7.

To reproduce:

- Go to an Android device (Google Pixel 8). Note: tested in Google Pixel only because full screen is not available on Samsung Galaxy devices now.
- Open a media object page with captions in Chrome. Example: https://avalon-dev.dlib.indiana.edu/media_objects/g158bh28p
- Start playback. Captions look ok when playing video in browser
- Start playback in full-screen. Captions are really big
- The caption settings seem normal (100%).

I believe there was some setting or change in video.js 8 that resolved this issue? Perhaps that needs to be double-checked to see if something is over-writing it?

<img width="359" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNzFpQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--579c0206d77d53b341b2281a4dd87ac4b465654b/screenshot-Google%20Pixel%208%20Pro-14.0%20%282%29.png" alt="screenshot-Google Pixel 8 Pro-14.0 (2).png" />

**Comment by elynema** [comment]
@charumitraravi Can you QA this one?

**Comment by charumitraravi** [comment]
QA completed. The size of the captions on android devices (Samsung, pixel) looks normal now.
