### ISSUE TITLE
[BUG] Custom start not working in iOS native player

### ISSUE THREAD

**Issue by Dananji** [samvera-labs/ramp#530]
### Description

When there's a custom start time for the media, it seems iOS native player is not picking it up. Native player always starts from zero.

This was found in the demo site sample manifest, where it had `start` property at the Manifest-level to set the start time of playback.

Related cookbook recipe to test: https://iiif.io/api/cookbook/recipe/0015-start/

### Done Looks Like
- [ ] iOS native player start playback at given start time when there's a start time specified for the Canvas

**Comment by elynema** [comment]
This should be tested in playlists. If it causes problems with playlists, we should tag this as part of 7.8 release.

**Comment by elynema** [comment]
If you use a section level URL in Avalon and then add a timestamp to it, users will see an issue in native player. Avalon doesn't currently generate any URLs like this.

Playlists are working fine.

**Comment by elynema** [comment]
This needs proper testing, so wait until next release, rather than rush out this release.

**Comment by joncameron** [comment]
Working in iOS 16.5 Safari 👍
