### ISSUE TITLE
Update vtt / srt validation for hours

### ISSUE THREAD

**Issue by elynema** [samvera-labs/ramp#537]
# Description

Technically, vtt and srt file formats are required to either have no digits for the hour in the timestamp, or 2 digits. Currently the validation in the Ramp transcript component allows 1 digit in the hour in the timestamp.

# Done Looks Like

 - [x] Ramp shows an error if a vtt or srt transcript has a single digit for the hour

**Comment by masaball** [comment]
[amp-demo-amia-transcript (2).txt](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBK2VlQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--6896494d7062ff428205c17e7d5861bdf5a7d5c8/amp-demo-amia-transcript%20%282%29.txt)

**Comment by joncameron** [comment]
https://avalon-dev.dlib.indiana.edu/media_objects/bc386j28j
