### ISSUE TITLE
Selecting Playlist Item from List Changes Autoplay Behavior

### ISSUE THREAD

**Issue by joncameron** [samvera-labs/ramp#551]
# Description
When a user manually selects any playlist item in the navigation, it kind of turns auto-play off (not the toggle, just the way that the playlist behaves). If I select a playlist item, and then start playing it, the next playlist item does not play automatically. It has to be manually played. The next inaccessible item will count down, but accessible content will not actually play and the following item in the playlist does not load and start playing automatically as would be expected.

# Done Looks Like 
- [x] Selecting a playlist item does not affect the autoadvance and play behavior when autoplay is enabled

**Comment by elynema** [comment]
@joncameron Just noting that this issue does seem to be a regression from 7.7.2. Did you want to pull it into 7.8 or no?

**Comment by joncameron** [comment]
I think it would be good to fix this—added to 7.8.

**Comment by joncameron** [comment]
Could no longer reproduce.
