### ISSUE TITLE
Previous/Next button bugs in mobile devices

### ISSUE THREAD

**Issue by Dananji** [samvera-labs/ramp#552]
### Description

From https://github.com/samvera-labs/ramp/issues/548;
- In Safari on iPad, if I advance to or select item 2, the next/previous canvas button will not return to me to item 1 (an inaccessible item) or item 3 (an accessible item). This was not observed on desktop.
- In Safari on iPad, if I select 29, the previous and next canvas buttons do not work (nothing happens when I click them). This was not observed in Safari on desktop (worked properly). 
- If I use the next canvas button to advance to 29, the previous canvas button skips 28 (an inaccessible item). Observed in Safari on desktop and iPad. In Chrome on Android, the previous canvas button returns to 28 as it should, but sometimes there is a gray overlay.

### Example
https://avalon-dev.dlib.indiana.edu/playlists/5

### Environment
- Safari on iPad
- Chrome in Android

### Done Looks Like
- [x] Previous/next in the control bar changes the canvas as expected when pressed
- [x] Previous/next buttons goes back/forward only one canvas respectively when pressed

### Related issues
- https://github.com/samvera-labs/ramp/issues/548
- https://github.com/samvera-labs/ramp/issues/501

**Comment by joncameron** [comment]
I could no longer reproduce these issues in iPad Safari.
