### ISSUE TITLE
[BUG] Previous canvas button does not send user to previous canvas in Safari

### ISSUE THREAD

**Issue by elynema** [samvera-labs/ramp#561]
**Describe the bug**
Sometimes, the previous canvas button seems to send user to the previous canvas, but then jump back to the canvas the user was just on. This happens intermittently, but has been seen in Safari on both avalon-dev and with the same playlist on the Ramp demo site.

So far, we've only seen this happen in this particular instance, so not sure if it is an issue with this playlist item or a larger problem.

**To Reproduce**
1. Go to playlist https://avalon-dev.dlib.indiana.edu/playlists/5
2. Select playlist item 26 (do not play it)
3. Use next canvas button to advance through to item number 29
4. Use the previous canvas button to go backward.
5. when going back from playlist item 28 to playlist item 27, the playlist jumps to 27 and then back to 28.

**Expected behavior**
When using the previous canvas button to move from playlist item 28 to playlist item 27, the user should end up at playlist item 27, not be re-directed back to playlist item 28.

**Desktop (please complete the following information):**
 - OS: Mac
 - Browser : Safari
 - Version 17.5 (17618.2.12.111.5, 17618)

**Comment by joncameron** [comment]
Needs to be retested; not able to reproduce currently.

**Comment by joncameron** [comment]
Could not reproduce.
