### ISSUE TITLE
[BUG] Results from content search not displayed or highlighted in transcript when they include non-alphanumeric characters

### ISSUE THREAD

**Issue by elynema** [samvera-labs/ramp#564]
**Describe the bug**
When the term(s) entered into the transcript search box container certain non-alphanumeric characters, the transcript search says 'no results found' and does not highlight results in the transcript, even though hits are being returned from the content search API itself.

**To Reproduce**
1. Go to the transcript for the first section: https://avalon-dev.dlib.indiana.edu/media_objects/gf06g267d
2. Enter one of the following searches into the transcript search box:
3. [THEME MUSIC]
4. --Television 
5. J-U-N-G
6. "Dear
7. The transcript search says 'no results found' and no results are highlighted in the transcript.

**Expected behavior**
If there are results returned from the content search response, they should be displayed as results in the transcript component. There will be times when the content search strips some of these characters from its search, so there are responses that do not contain them. Examples are the '--television' search. Will that be a problem for displaying those as a match?

**Screenshots**
<img width="1402" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNnZSQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--e4d49eb1bcf63e9bea1062703551decbb7ab10a2/image.png" alt="image.png" />

**Desktop (please complete the following information):**
 - OS: Mac
 - Browser: Chrome and Safari
 
**Additional context**
This was discovered during testing for #5897 in avalon repo, so more details are available there.

**Comment by joncameron** [comment]
These are now matching as expected.
