### ISSUE TITLE
[BUG] Auto-play does not start next item in playlist if user clicks next canvas to inaccessible item

### ISSUE THREAD

**Issue by elynema** [samvera-labs/ramp#580]
**Describe the bug**
If the user selects an item that is immediately before an inaccessible item, starts it playing, then hits 'next canvas' to the inaccessible item, and then allows the inaccessible item to expire, the next playlist item does not automatically begin playing.

This is an edge case remaining from testing behavior around auto-play in playlists with the new prevous/next button functionality for inaccessible playlist items. 

**To Reproduce**
1. Go to avalon-dev, do not log in.
2. Go to playlist: https://avalon-dev.dlib.indiana.edu/playlists/5
2. Make sure auto-play is turned on
3. Select playlist item 18. Hit the play button to start playback
4. Before item 18 is finished playing, hit the next canvas button.
5. Playback proceeds to the inaccessible playlist item 19. 
6. Let the 10 seconds expire
7. Playback proceeds to the accessible playlist item 20.
8. However, playback of playlist item 20 does not begin automatically.

**Expected behavior**
Since auto-play is turned on, playback of any accessible playlist item should begin automatically.

Note: Sometimes this works as expected the first time attempted after the playlist page loads. If so, try again. I have found that the second try it stops working. This can also be tested on any single inaccessible playlist item (there are several in this playlist).

**Desktop (please complete the following information):**
 - OS: Mac laptop
 - Browser: Chrome and Safari

**Comment by Dananji** [comment]
Fixed behavior in PR:
- If the user has started playback at some point play the next item after an inaccessible item when the timer ends
- If the user has not started playback at any point/started playback and paused it before reaching the inaccessible item don't play the next item after an inaccessible item when the timer ends

**Comment by elynema** [comment]
This is probably a regression of us re-organizing the way that video.js initializes in 7.8.

**Comment by joncameron** [comment]
Can no longer reproduce.
