### ISSUE TITLE
[BUG] Playback does not begin when audio is muted on iOS (iPhone/iPad)

### ISSUE THREAD

**Issue by elynema** [samvera-labs/ramp#583]
**Describe the bug**
When the audio is muted, playback does not begin for audio only items on iOS (both iPhone and iPad). This was replicated in Safari, but reported to be observed across browsers.

**To Reproduce**
1. Go to https://avalon-staging.dlib.indiana.edu/media_objects/rf55z7692 on iPad or iPhone (iOS17) in Safari.
2. Make sure volume is muted.
3. Start playback.
4. Audio will not start and the playback head will not move.
5. Unmute volume.
6. Playback will start with audio.
7. Note: this can be intermittent. It seems to happen most reliably when the audio is already muted, so after page refresh after you have muted audio.

**Expected behavior**
Playback should begin even if audio is muted.

**Screenshots**

https://github.com/user-attachments/assets/692ef80a-c472-45a5-9195-76b295aad56f

**Smartphone (please complete the following information):**
 - Device: iPad/iPhone
 - OS: iOS17
 - Browser: Safari (and presumably Chrome)

**Comment by elynema** [comment]
Could it possibly be a feature of iOS that playback of an audio item will not begin if it is muted?

**Comment by Dananji** [comment]
I tested the [audio cookbook recipe](https://ramp.avalonmediasystem.org/?iiif-content=https://iiif.io/api/cookbook/recipe/0002-mvm-audio/manifest.json) in this specific environment, and it plays and updates the UI as expected with these settings.

**Comment by Dananji** [comment]
I tested with an [audio manifest](https://dc.library.northwestern.edu/items/774273ef-953d-40a3-8b4e-47ac570e08fd) from one of Northwestern's collections, and observed the same behavior.

I tested this issue in Chrome on iOS in both iPhone and iPad, and observed the same behavior.
In desktop browsers; both Firefox, Chrome played the media when muted but not Safari.

I was not able to find anything that explains this behavior in relation to Apple's system settings on the internet.

One solution we could implement is unmute the audio player on page load in the environments we are seeing this behavior.

**Comment by elynema** [comment]
In Safari, when audio is muted, it never gets to the point where the player is ready to play the media. Same issue when we were trying to activate the buttons in the iOS player b/c the player was not ready enough to have everything ready to play, even when the loaded metadata event has fired. Another event called 'canPlay' - ready state never reaches 4 in Safari when the audio is muted.

**Comment by abankhele** [comment]
I can replicate this issue on ipad and iPhone (iOS17) in Safari. It only happens when you mute the media player refresh the URL and then click play on the audio.

**Comment by elynema** [comment]
We do not see this problem if you just load the page, mute the audio, and then play the media.

**Comment by elynema** [comment]
Not 100% sure when we pulled a new Ramp build into Avalon, so I've asked Akanksha to test this on the Ramp demo site.
