### ISSUE TITLE
[BUG] CC widget is not aligned on mobile devices

### ISSUE THREAD

**Issue by elynema** [samvera-labs/ramp#586]
**Describe the bug**
The CC widget is not properly aligned in the center of the green underline that displays when captions are turned on in Ramp. This is not an issue on Chrome / Safari on desktop, but is noticeable in Android and iOS
**To Reproduce**
1. Go to any item with captions on avalon-staging (ex: https://avalon-staging.dlib.indiana.edu/media_objects/9c67wm82b, third section) on iPhone, iPad, or Android device.
2. Turn captions on if they are not already on.
3. The CC icon is not centered above the green underline. On iPad (Safari) for example, it is right-aligned with the green underline, but is significantly narrower (see screenshot).

**Expected behavior**
Across all device contexts, the CC icon should be centered above the green underline when captions are turned on.

**Screenshots**
![screenshot-iPad Air 6-17 0](https://github.com/user-attachments/assets/96dcdd5c-6fd8-418c-89a6-4e3b97c3760d)

**Smartphone (please complete the following information):**
 - Device: iPhone, iPad, Android Pixel
 - Browser: Safari on iOS; Chrome on Android

**Comment by elynema** [comment]
Could just be that the green underline is not properly aligned.

**Comment by joncameron** [comment]
Properly aligned now:
![Screenshot 2024-08-28 at 3 45 49 PM](https://github.com/user-attachments/assets/ac35a3e7-fb8d-4a21-b279-a53777a2ed2b)
