### ISSUE TITLE
General code cleanup

### ISSUE THREAD

**Issue by Dananji** [samvera-labs/ramp#593]
# Description

Ramp has a lot of code that we've been adding on top of things during different stages of development, and some these codes don't make sense to a new person looking at the code or sometimes someone who's been working on it since the beginning (me).

So we need to to some generic code cleanup around the following general areas;
- parsing
- JSON object creation to pass around values into different parts of the code
- player event handling in different components and modules

This work can be performed after the state management and manifest parsing changes are completed—this is basically cleaning up what is left after that work. We might need to refine the above list at that point in time.

# Done Looks Like
Code cleanup for:
- [x] adding comments to describe things when they are complex and make the code easier to understand
- [x] parsing
- [x] JSON object creation to pass around values into different parts of the code
- [x] use `cx` library for conditional className building
- [x] player event handling in different components and modules
- [x] update documentation if needed
- [x] cleanup intervals and timeouts on component unmount events

**Comment by joncameron** [comment]
Scope for this will probably be smaller after working through state management and manifest parsing in the other Ramp refactor issues.

**Comment by joncameron** [comment]
This can be estimated after work has been completed on samvera-labs/ramp#605 and 606

**Comment by elynema** [comment]
@abankhele Assigned this one to you as well; it will be covered by the full regression testing on Ramp.
