### ISSUE TITLE
Change Manifest Parsing Strategy

### ISSUE THREAD

**Issue by joncameron** [samvera-labs/ramp#606]
# Description
Moving manifest parsing to a central location so it can be managed with state that doesn't require components to do unnecessary processing.

This can be done before or in parallel with the state management investigation (samvera-labs/ramp#605).

These changes will require thorough testing. Most of it could be handled in unit testing; tests will most likely need to be added as parsing is changed. This should not change functionality, but with changing the parsing strategy it should still be expected that all the fields are still coming to the right place for consumption by Ramp components.

# Done Looks Like
- [ ] Bring manifest parsing code into a single place
- [ ] Manifests only need to be read and parsed once
- [ ] Create a single data structure that can be used to represent manifest data across components
- [ ] Remove unnecessary state values or duplicates from different components
- [ ] Test across Ramp components to ensure they're populating data correctly from manifest data

# QA
- Test this alongside Ramp #605, as both introduce major infrastructure changes to Ramp
- Test functionality across all Ramp components: media player, transcripts, files, metadata, structure, playlists, auto-play, markers

**Comment by elynema** [comment]
Dananji is testing vault and manifesto for parsing manifests. Vault errs when we have inaccessible items with no ID.

**Comment by joncameron** [comment]
👍
I created samvera-labs/ramp#656, a bug that looks like it may be with the demo site.
