### ISSUE TITLE
Improve media label generation

### ISSUE THREAD

**Issue by masaball** [samvera-labs/ramp#610]
# Description
This is a bit of an edge case, but the [logic for grabbing the manifest label](https://github.com/samvera-labs/ramp/blob/40953fb31a1e2a3d67890de5f1b9681135fc2343/src/components/MediaPlayer/MediaPlayer.js#L176C9-L176C65) for use in the video player's titlebar causes an error when there is not a manifest label. In the real world this should not be much of an issue because label is a required field on the manifest, but it could still cause problems with malformed manifests.

Should we silently skip that logic if the manifest label is not defined so that Ramp will still display everything? Or should we enforce the label requirement and catch the current error generated to raise a more informative error?

<img width="1135" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNkFzQmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--3a2ca9a4f7144f779f3fc6567d982e51e9fa305a/Screenshot_20240802_131817.png" alt="Screenshot_20240802_131817.png" />

Another option—could we just assign a default value if there is none? i.e.  `label = manifest.label || ""`

# Done Looks Like
- [ ] label value defaults to a blank string if not present within the manifest (manifest label check fails)

**Comment by joncameron** [comment]
👍
