### ISSUE TITLE
Player replays last section/single section item in a loop

### ISSUE THREAD

**Issue by Dananji** [samvera-labs/ramp#624]
### Description

For single section items the player is replaying the section.  For multi-section items it is replaying the last section.

### Done Looks Like
- [ ] Once player reaches the end of a single section item
  - [ ] stop playback
  - [ ] don't reset current time to zero and show replay icon instead of play/pause icon in the controls

- [ ] Once player reaches the end of the last section in multi-section item  or a playlist
  - [ ] stop playback
  - [ ] stay on last section / last playlist item (don't go back to the beginning)
  - [ ] don't reset current time to zero and show replay icon instead of play/pause icon in the controls
  - [ ] replay icon replays the current section / playlist item

**Comment by elynema** [comment]
Hold this until Ramp state management / code cleanup is complete.

**Comment by joncameron** [comment]
Worked as expected in Ramp demo site for single- and multi-section items.
