### ISSUE TITLE
Ramp Demo Site Not Updating Video

### ISSUE THREAD

**Issue by joncameron** [samvera-labs/ramp#656]
# To Reproduce
- Go to https://ramp.avalonmediasystem.org
- Put in a url in the Manifest URL field and select "Set Manifest"
- The thumbnail and other aspects of Ramp populate with data from the manifest, but the video only ever plays as the Lunchroom Manners video in the default manifest for the Ramp demo site

A direct link to load the manifest URL in works as expected:
https://ramp.avalonmediasystem.org/?iiif-content=https://avalon-dev.dlib.indiana.edu/media_objects/gf06g267d/manifest.json

# Done Looks Like
- [ ] "Set Manifest" on the demo site loads the requested manifest to update the video data in addition to the other properties

**Comment by masaball** [comment]
As far as I can tell, this does seem to be a state management issue. There is a `VideoJSRef` variable/hook that is getting set on the initial page load but is not being updated when loading the new manifest. I haven't been able to determine how to trigger the ref to update/reload though.

**Comment by abankhele** [comment]
The set manifest works fine now. The thumbnail loads on clicking "Set Manifest" button and on clicking play button starts the video of the provided manifest URL in the media player
<img width="1459" alt="Screenshot 2024-10-21 at 10 23 40 AM" src="https://github.com/user-attachments/assets/9c7f3cb2-6cc4-4665-a477-42b06634c0a8">
<img width="1461" alt="Screenshot 2024-10-21 at 10 24 48 AM" src="https://github.com/user-attachments/assets/2953fc59-8294-467b-9911-53b257e2139e">
