### ISSUE TITLE
Replace new volume control

### ISSUE THREAD

**Issue by elynema** [samvera-labs/ramp#657]
# Description

The new volume control button in Ramp that is shaped like a triangle does not allow for as easy adjustment of volume as the slider and does not provide a single click to mute/ un-mute.

Consider bringing back the vertical slider. We have numerous other widgets in Ramp that overlay the progress bar with a menu, so it seems like it could work for the vertical slider as well. Alternatively, all the popups that are used by widgets, including the vertical slider, could be placed above the progress bar.

# Done Looks Like
- [x] Volume control component changed to the previous style: click to enable/disable with a slider overlay for the volume

**Comment by Dananji** [comment]
Note for testing:
- All popup menus were moved to display above progress-control
- All popup menus (captions, quality selection, file download, playback rate) are now displayed only on `click`/`keydown` (`Enter`/`Space` on focus, when using keyboard navigation) events. Previously these menus were shown on both `click`/`keydown`/`hover` event.

**Comment by elynema** [comment]
Tested across Android, iPad, Safari and Chrome desktop, as well as audio and video embeds. The audio control itself looks like it is working fine in al these contexts.
