### ISSUE TITLE
[BUG] Captions display over top of progress bar

### ISSUE THREAD

**Issue by elynema** [samvera-labs/ramp#658]
**Describe the bug**
With the new multi-line progress bar + video.js widget display, multi-line captions are overlapping the progress bar. The captions should not overlap the progress bar.

**To Reproduce**
1. Go to a record in avalon-dev with captions: https://avalon-dev.dlib.indiana.edu/media_objects/37720c78r/section/cv43nw85w
2. Begin playback with captions turned on
3. You will see the captions overlap the progress bar once there is a multi-line caption.

**Expected behavior**
The captions should display above the progress bar. Note: LinkedIn Learning uses video.js as well, and they have the captions move up (when the progress bar / widgets are visible) and down (when the progress bar and widgets disappear). This would be a cool solution.

This has not been tested on mobile devices, so not sure if it will work differently there.

**Screenshots**
Current display in Avalon:

https://github.com/user-attachments/assets/7d4e3c11-a1f5-4922-a0a1-7300ba7c8842

LinkedIn example:

https://github.com/user-attachments/assets/624056a5-89d8-4edc-ac16-086580230006

**Desktop (please complete the following information):**
 - OS: MacOS
 - Browser: Chrome
 - Version: 129.0.6668.70

**QA**

- [x] Test caption display and progress bar on Chrome desktop, Safari on iPhone/iPad, and Chrome on Android

**Comment by joncameron** [comment]
Could be a CSS change; VideoJS also has options that could be used for this purpose.

**Comment by elynema** [comment]
Created https://github.com/samvera-labs/ramp/issues/727 for issue with large caption text size on iPad.
