### ISSUE TITLE
Explore background to bring together progress bar and video.js widgets

### ISSUE THREAD

**Issue by elynema** [samvera-labs/ramp#659]
# Description

In the new multi-line display of progress bar and video.js widgets in Ramp, there's not background color that brings those 2 elements together into a group. Some type of gray background could be useful here.

Current Ramp in Avalon:
![image](https://github.com/user-attachments/assets/d0bfda40-c154-4637-99e0-168a024073fd)

Current MCO:
![image](https://github.com/user-attachments/assets/c431b360-da4b-4b58-8052-fc713c53ec80)

LinkedIn example:
![image](https://github.com/user-attachments/assets/5e421411-620b-454f-b503-5cba9c4f5f04)

# Done Looks Like
- [ ] Gather more example of UI design for demarcating the player controls from the video image
- [ ] Generate some UI design proposals for possible changes to the contrast between player controls and other elements of the media player

**Comment by Dananji** [comment]
I found a VideoJS plugin which brings together icons in the progress bar: https://github.com/samueleastdev/videojs-setting-menu
There are 2 reasons why we can't use it out of the box;
1. When I tried to install it using `yarn` into Ramp, it gave an error. Related to other VideoJS dependencies we are using in Ramp
2. We can't customize the icons and menus that goes into the plugin at the moment. i.e. it has a static set of icons and this cannot be changed when initializing in Ramp

So, I brought in the code to Ramp as a custom plugin to see whether we can change things around to include what we want in the menu and I got the following;

Settings menu;
<img width="648" alt="Screenshot 2024-10-25 at 9 17 48 AM" src="https://github.com/user-attachments/assets/1f191328-24ef-4e90-bbe4-9459b09cba3b">
Captions menu opened within settings;
<img width="648" alt="Screenshot 2024-10-25 at 9 17 59 AM" src="https://github.com/user-attachments/assets/4ffbecb3-d739-441b-a151-71b9676f557d">

Work to do:
1. Fix the settings menu icon and styling to match Ramp
2. Check for accessibility when using the settings menu
3. When using the settings menu; the icons that goes into it still needs to be initialized as control-bar children in VideoJS options list, which for a couple of seconds shows up in the control bar when player is loading
4. Customize the menus that goes into settings menu using props like `enableFileDownload`

**Comment by Dananji** [comment]
@joncameron and @elynema I forgot ask about this in Backlog buddies. Is there any preferred changes to the popup menus we can do based on these findings? Or do we need further investigation?

**Comment by elynema** [comment]
We are looking at shading behind the widget bar and progress bar, not behind the popup menus:

<img width="1206" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBL3FHQnc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--33e39808473ce5038fc03a1dc7efdd8a19a8d941/374706707-5e421411-620b-454f-b503-5cba9c4f5f04.png" alt="374706707-5e421411-620b-454f-b503-5cba9c4f5f04.png" />

LinkedIn Learning (above) does have a shading you can see, although opacity decreases as the shading moves up to the progress bar. Looking at Youtube, there is a very subtle shading at the bottom that seems to fade away before the progress bar. I didn't see any shading on Netflix.

Given what I was seeing with Youtube, we might want to come back to this after we add some padding around the progress bar and see if we feel like it is still needed.

**Comment by elynema** [comment]
With padding changes from #687, I think things look ok and we don't need any changes to background color / opacity.
