### ISSUE TITLE
'Close/Expand Section' Button is not functioning as expected

### ISSUE THREAD

**Issue by abankhele** [samvera-labs/ramp#663]
**Description**
The collapsible button for sections beneath the media player on [Avalon Dev](https://avalon-dev.dlib.indiana.edu/) is not functioning as expected. The sections are neither collapsing nor expanding when the buttons are clicked.

**To Reproduce**

1. Go to [Avalon Dev Media object](https://avalon-dev.dlib.indiana.edu/media_objects/3j3332278).
2. Click on the 'Close 2 Sections' button.
3. Notice that the sections related to "Lunchroom Manners" are not hidden as expected.
4. Manually click on the 'Lunchroom Manners' section to collapse it.
5. Now, click on the 'Expand 2 Sections' button.
6. Observe that the sections do not expand as intended.

**Expected behavior**

1. Clicking 'Close 2 Sections' should collapse the sections beneath the media player.
2. Clicking 'Expand 2 Sections' should reveal the hidden sections.

**Screenshots**
<img width="1357" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeFZBQnc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--96caed63ea265823a573e21d401b7d711bed9420/image.png" alt="image.png" />

<img width="1050" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeGhBQnc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--0852e770000321a4277d601e7c5816fb0cdfd962/image.png" alt="image.png" />

**Desktop :**
 - OS: macos
 - Browser : chrome, safari

**Smartphone :**
 - Device:  iPhone, ipad
 - OS: iOS18
 - Browser : chrome, safari

**Comment by joncameron** [comment]
See samvera-labs/ramp#645 for the issue that should resolve this issue

**Comment by joncameron** [comment]
Functioning as expected now!
