### ISSUE TITLE
Tracking bar attached to the media player is not functioning as expected

### ISSUE THREAD

**Issue by abankhele** [samvera-labs/ramp#667]
**Description**:
The tracking bar attached to the media player is not functioning as expected. When users click or drag the scrubber on the tracking bar, it should adjust playback based on the structure's timeline. However, the playback instead jumps to the corresponding time on the media player's general timeline, ignoring the structure's specific timeline.

**To Reproduce**

1. Navigate to '[Avalon-dev](https://avalon-dev.dlib.indiana.edu/)'.
2. Select Collections -> Choose any collection -> Select a Video Item (it must have a structure). Alternatively, use this [Video Item](https://avalon-dev.dlib.indiana.edu/media_objects/3j3332278) and [Audio Item](url). 
3. Select any structure that does not start at the beginning of the media file.
4. Click on the Toggle Track Scrubber to open the tracking bar attached to the media player.
5. Click on a point in the tracking bar or drag it forward or backward.
6. Observe that the media plays based on the media player’s general timeline, not the structure’s timeline.

**Expected behavior**
When interacting with the tracking bar (by clicking or dragging), the media should play based on the structure’s specific duration, not the overall timeline of the media player.

**Screenshots**
[Private Zenhub Video](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeWhSQnc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--d3a88b9132288bce6497acb5a9ed6c52c6498528/Screen%20Recording%202024-10-16%20at%204.40.10%E2%80%AFPM.mov)

**Desktop (please complete the following information):**
 - OS: MacOS, Windows
 - Browser [chrome, safari]

**Smartphone (please complete the following information):**
 - Device: [iPhone6]
 - OS: [e.g. iOS18]
 - Browser [safari]

**Comment by elynema** [comment]
Dananji tested this on Ramp demo site and it was working properly. Needs to be tested again once we get a new Ramp build into Avalon.

**Comment by elynema** [comment]
Sample audio only item: https://avalon-dev.dlib.indiana.edu/media_objects/fn106x94r

This seems to be working fine in Chrome and Safari on desktop as well as Chrome on Android. I am having a lot of trouble using the structure to navigate on iPad/iPhone Safari (spinning), so I can't fully test there.
