### ISSUE TITLE
[BUG] Audio only items do not auto-play next section on Safari (desktop, iPhone)

### ISSUE THREAD

**Issue by elynema** [samvera-labs/ramp#672]
# Description

For audio recordings that have multiple sections, when the first section reaches the end, the second section does not auto-play. Instead, playback stops at the end of the section. This was observed on Safari on desktop and iPhone. In addition, for a playlist where there are multiple audio recordings in a row, autoplay does not advance past the first audio file. 

Video recordings auto-play multiple sections fine. Audio recordings in Chrome are working for auto-play.

Example records for testing:

-  https://avalon-dev.dlib.indiana.edu/media_objects/fn106x94r
-  https://avalon-dev.dlib.indiana.edu/media_objects/gx41mh86p
-  https://avalon-dev.dlib.indiana.edu/playlists/5 (last 4 playlist items are from audio recordings)
  
Event handling _should_ be the same across audio and video and these changes should just be cosmetic

# Done Looks Like
- [ ] Playback continues to the next section/item in Safari when autoplay is enabled

**Comment by abankhele** [comment]
Tested in Safari on both desktop and iPhone for the mentioned items. Everything is working as expected; playback continues when autoplay is enabled.
