### ISSUE TITLE
[BUG] Problems navigating playlist items when first item is inaccessible

### ISSUE THREAD

**Issue by elynema** [samvera-labs/ramp#673]
# Description

If the first item in a playlist is inaccessible, and the user clicks Next (before auto-advance) or selects the next playable item in the playlist items, the next item to play will loop rather than advancing when it completes and all the other playlist items will not be selectable (nothing happens when you click on them).

If the user allows the first inaccessible item to advance without clicking Next or selecting another item, it will auto-advance after 10 seconds, skipping the next item in the playlist.

This was observed in Safari and Chrome on desktop, as well as Safari on iPhone.

Example playlist: https://avalon-dev.dlib.indiana.edu/playlists/5 

Auto-advance skips second item in playlist:

https://github.com/user-attachments/assets/4f564d74-fc46-4790-b9ff-790ec2c71bcd

Manually advancing the inaccessible item causes the next item to loop and then nothing happens when selecting other playlist items:

https://github.com/user-attachments/assets/68fc732c-c044-4eae-a39c-1e08632ec7e8

**Comment by elynema** [comment]
Note: I am also seeing this now for inaccessible items that are not the first item. If autoadvance is used, playback will skip the item immediately following the inaccessible item. Allow this playlist to autoadvance while logged out: https://avalon-dev.dlib.indiana.edu/playlists/178. After the second inaccessible item's timer runs out, the highlighting skips to the fourth item and the inaccessible error displays, but the audio from the skipped third item begins to play.

Probably related to ramp #680.

**Comment by Dananji** [comment]
> If the first item in a playlist is inaccessible, and the user clicks Next (before auto-advance) or selects the next playable item in the playlist items, the next item to play will loop rather than advancing when it completes and all the other playlist items will not be selectable (nothing happens when you click on them).

I was not able to reproduce this in `avalon-dev` in both Chrome and Safari on desktop.

> If the user allows the first inaccessible item to advance without clicking Next or selecting another item, it will auto-advance after 10 seconds, skipping the next item in the playlist.

I was able to reproduce this in `avalon-dev` in Chrome but not in the demo-site (for the same playlist).

**Comment by elynema** [comment]
Re-tested and agree wtih Dananji that I'm no longer seeing issues when using Next button or playlist items to navigate past the first inaccessible item in avalon-dev on Chrome, Safari, or iOS. Still seeing issues with the auto-advance as the new Ramp build isn't brought into avalon-dev yet.

Need to re-test all of these cases once we have a new Ramp build since there are code updates touching on this functionality.

**Comment by elynema** [comment]
Tested in Chrome, Safari, iPhone, and Android. I managed to have a weird glitch a couple of times on Android when I clicked the item immediately following the first inaccessible item in the playlists where it got stuck and didn't advance to the next item. I'm not able to get that to reproduce, so closing this as is.
