### ISSUE TITLE
Horizontal scroll bar for really long structure heading labels

### ISSUE THREAD

**Issue by Dananji** [samvera-labs/ramp#675]
## Description

When there are really long labels for sections in the structures, Ramp's StructuredNavigation component creates a horizontal scroll-bar.
### Example structure
From `avalon-dev`: https://avalon-dev.dlib.indiana.edu/media_objects/mw22v546v
![Screenshot 2024-10-23 at 2 33 05 PM](https://github.com/user-attachments/assets/1b206ed0-69b2-4424-91c4-da8bb55a7324)

## Done Looks Like
- [x] No horizontal scroll-bar is present in StructuredNavigation component
- [x] Wrap the label into new lines to fit the width of the structure container

## Notes
- When spaces are present in the string, wrapping with newlines is already taken care of
Related work: https://github.com/samvera-labs/ramp/pull/674

**Comment by elynema** [comment]
Looks good to me across Chrome, Safari, iPad, Android.
