### ISSUE TITLE
[BUG] No playhead visible in Safari on iPhone

### ISSUE THREAD

**Issue by elynema** [samvera-labs/ramp#678]
# Description

In Safari on iPhone, when the media item page loads, there is no playhead visible. This makes it pretty much impossible for a user to drag the playhead to scrub.

![image](https://github.com/user-attachments/assets/19bb680d-b19d-42e0-a22c-3e54a7c493de)

# Done Looks Like
- [x] Playhead appears in the media player and functions as expected
- [ ] Re-test in avalon-dev

**Comment by joncameron** [comment]
This is fixed and Ramp; retest and close with progress bar work in the latest code.
