### ISSUE TITLE
[BUG] Clicking on marker doesn't work when first load playlist page in iPhone Safari

### ISSUE THREAD

**Issue by elynema** [samvera-labs/ramp#679]
# Description

When the user first loads a playlist page, and then opens the markers and clicks on a marker, the media player spins. If you click play while the media player is spinning, the native player opens, but playback begins at the beginning of the playlist item, not at the marker. 

This is working fine in Chrome on desktop.

https://github.com/user-attachments/assets/0c89e309-85f9-4a84-82a7-69ffb6808d24

# done Looks Like

 - [ ] When you select a marker, the media player should jump to that time point regardless of whether the user previously started playback
 - [ ] When you begin playback after selecting a marker, playback should begin at the marker, even in the iOS native player

**Comment by elynema** [comment]
Related to Ramp #677 and #694 (probably).

**Comment by joncameron** [comment]
Tested on iPhone 14 v16.3 in Browserstack and clicking the marker works as expected to advance the playhead successfully before playback starts.
