### ISSUE TITLE
[BUG] Issues when last item in playlist is inaccessible

### ISSUE THREAD

**Issue by elynema** [samvera-labs/ramp#680]
**Describe the bug**
When the last item in a playlist is inaccessible, we are seeing several issues:

- If you click next to the last inaccessible item while the previous item is playing, the audio from the previous item continues to play even though the player shows the inaccessible item message.
- When you hit the previous button from the last inaccessible item, it sometimes does not return to the previous item 

These issues were observed in both Chrome and Safari on desktop.

**To Reproduce**
1. Load one of these playlists as an unathenticated user: https://avalon-dev.dlib.indiana.edu/playlists/96 or https://avalon-dev.dlib.indiana.edu/playlists/178
2. Select the item before the last inaccessible item and play it.
3. Either hit the next canvas button in the media player or select the last inaccessible item in the list of items
4. The error will show in the media player, but the audio from the previous item continues to play.
5. Select the item before the last inaccessible item and begin playback if not playing.
6. Pause playback.
7. The playlist will skip to the last inaccessible item after a few seconds, playing the soundtrack to the previous item.
8. If you hit previous, the playlist will not return to the previous item.
9. At this point, the playlist is pretty messed up and if you click on another playlist item, it will quickly advance through the entire playlist.

**Expected behavior**

- [ ] When I advance to an inaccessible item, including the last item in a playlist, the audio from the previous item should stop playing
- [ ] Pausing playback on an item immediately preceding an inaccessible item should not cause the playlist to skip to the next playlist item.
- [ ] Should be tested to work properly on Safari iPhone and Android Chrome, as well as Chrome / Safari on desktop.

**Screenshots**
 Note: you can't hear the audio here, but when I click the next canvas button to get to the last playlist item (inaccessible), the audio from the prior item continues to play.

https://github.com/user-attachments/assets/b8840d9f-c076-434c-b424-0448a61ac3b3

**Desktop (please complete the following information):**
 - OS: MacOS
 - Browser: Chrome
 - Version 129.0.6668.101

Not tested yet on smartphone

**Additional context**

**Comment by Dananji** [comment]
I tested this on Chrome and Safari on desktop in my local Avalon instance with the latest Ramp code, and I was not able to reproduce the bugs reported in this ticket.
We can re-test this once a new Ramp build is brought into `avalon-dev`.

**Comment by elynema** [comment]
@Dananji I am not able to replicate the first half of the problem in Chrome, but I can replicate the second part:

1. Go to playlist:
2. Click on the second item (last one before inaccessible item)
3. Play item
4. Click next canvas to last inaccessible item
5. Click previous or click on second item in playlist items to return to previous item
6. Click next canvas to move again to the last item
7. Click previous again.
8. Click next canvas
9. Click previous again. Usually on the third try, the player will show the inaccessible message for the last item, even though the audio on the item before is playing.

Usually on the 2nd or 3rd time you try to flip back to the item that preceeds the inaccessible item, the media player video skips back ahead to the inaccessible message while the audio keeps playing.

**Comment by Dananji** [comment]
This fix is not in `avalon-dev` yet, so we are still seeing the second part of the bug reported in this ticket in `avalon-dev`. I tested this in my local avalon instance, to make sure this is not just working in the demo site because I was seeing that in the [previous issue](https://github.com/samvera-labs/ramp/issues/673).

**Comment by elynema** [comment]
@Dananji Does that mean this was fixed by a commit for the other inaccessible item bug #673 since there aren't any commits for this bug?

**Comment by Dananji** [comment]
Yes, that is correct.

**Comment by elynema** [comment]
Tested on Chrome, Safari, iPhone, and Android. Looks good.
