### ISSUE TITLE
[BUG] Issues with captions and scrubbing on Safari iPhone

### ISSUE THREAD

**Issue by elynema** [samvera-labs/ramp#681]
**Describe the bug**
Caption selections do not persist if the user scrubs between changing settings.

This was not replicated on desktop. Not yet tested on Android Chrome.

**To Reproduce**
1. Go to https://avalon-dev.dlib.indiana.edu/media_objects/3j3332278
2. Begin playback so that scrubbing will work in the future.
3. Stop playback to return to media objects page.
2. Set captions off
3. Scrub ahead in video
4. Set captions back on
5. Begin playback
6. Captions are not on in either iOS native player or when stop playback and return to media item page.

**Expected behavior**

- [ ] Caption settings set immediately after scrubbing should be maintained.

**Screenshots**

https://github.com/user-attachments/assets/2634a306-1057-40da-93a1-0215dfcdb304

**Smartphone (please complete the following information):**
 - Device: iPhone 15 Pro
 - OS: iOS 17
 - Browser Safari

**Comment by elynema** [comment]
Note: based on the video, this may actually be an issue with actually getting the caption option selected isntead of the time rail.

**Comment by joncameron** [comment]
Needs to be retested; probably related to the bug about incorrect selection of elements.

**Comment by elynema** [comment]
This is working fine on iPhone now; the problem was that when trying to turn the captions back on, the click was hitting the progress bar as opposed to actually selecting the caption, so the captions weren't turned back on in web or native player. This was resolved by moving the popup menus so the user isn't clicking the progress bar instead of the menu option.

Closing this issue.
