### ISSUE TITLE
Progress bar Styling Changes

### ISSUE THREAD

**Issue by joncameron** [samvera-labs/ramp#688]
# Description
The current behavior of the progress bar often makes it difficult to interact with.  Changes like removing the animation to provide a stable area of interaction in favor of increasing the initial height of the progress bar will make these events fire over a larger area.

# Done Looks Like
- [x] Remove animation that changes height of the progress bar
- [x] Increase general height value of the progress bar (match full height on hover)
- [x] Broader area for progress bar for interaction events
- [x] Progress ball appears in front of transparent load progress bar

# Examples
The target area for the mouseover is too small, making actions unavailable for users even in some cases where the mouse cursor is over progress bar:
![Oct-30-2024 13-43-36](https://github.com/user-attachments/assets/979db78e-eecc-4804-82e6-40bf1b8a559d)

The playhead/ball icon is behind the colored strips representing load progress:
![Screenshot 2024-10-30 at 1 48 05 PM](https://github.com/user-attachments/assets/18b152d4-d19c-4a3f-a9c2-8d8971eb167f)

Mockup of the progress bar with a greater height value: 
![Screenshot 2024-10-30 at 1 47 01 PM](https://github.com/user-attachments/assets/9389bf87-fb39-4617-ac29-ce18de2fa228)

**Comment by joncameron** [comment]
Increasing the height of the progress bar element should be easy; increasing the area of interaction might be more difficult.

**Comment by elynema** [comment]
I have noticed one issue. When I scrub by clicking on the progress bar or dragging the playhead, the progress bar gets a sort of yellow glow around it. This remains until I pause and restart the audio/video or click elsewhere on the page. This doesn't happen when just playing / pausing / starting the playback or when using structure to navigate. Observed in Chrome and Safari on desktop. Also observed in Safari on iPhone and iPad with an audio item (but only on the second click in the progress bar) as well as on Android Chrome.


https://github.com/user-attachments/assets/5f5dcf51-035e-45c0-b7bb-231ab719d176

Desired behavior would be to remove that highlighting on the progress bard when the user scrubs (clicks in progress bar or drags the playhead).

**Comment by elynema** [comment]
@joncameron Original styling requests in Done Looks Like look good to me across all platforms. You may want to take a quick look to see if you are happy as well.

Still need to QA the highlighting fix, which is currently on Ramp demo site only.

**Comment by joncameron** [comment]
Yes, this looks good! I'm happier with this, and comparing between avalon-dev and the Ramp demo site makes it clear the progress bar looks better without the highlighting as well.
