### ISSUE TITLE
[BUG] Selecting tracks does not properly adjust playback on iPhone Safari

### ISSUE THREAD

**Issue by elynema** [samvera-labs/ramp#694]
**Describe the bug**
When selecting a segment / track from the structure for a media object, various problem can occur, such as the playhead not moving, the media player spinning, and then playback starting at the beginning instead of the selected section.

This is not just an issue with the native player, as the playhead does not move properly in the web player before playback begins.

This does not seem to be happening on Chrome on desktop.

**To Reproduce**
1. Go to https://avalon-dev.dlib.indiana.edu/media_objects/fj236208t
2. Click on the second track for the first section
3. The time advances to 1:00/9:32, but the media player spins and playhead does not move. It seems to keep spinning forever?
4. Begin playback.
5. Native player opens at playback begins at beginning of video, not at the 1:00 minute mark
6. Check the progress bar in the native player. It is stuck (not advancing). It might be stuck at 0:00 or saying 1:00.
7. Pausing / re-starting playback in native player doesn't change anything.
8. When native player is closed, the media player on the web page is still spinning and time still reads 1:00 in the progress bar area and playhead now seem to be at 1:00 in the progress bar, even though media is paused at just a few second in.

**Expected behavior**

**Screenshots**

https://github.com/user-attachments/assets/78a2b15b-a6de-4842-9e8b-3c8a5a054ce2

**Smartphone (please complete the following information):**

**Additional context**

**Comment by joncameron** [comment]
Same issue as seen with scrub actions—no shared state with native player. iOS Safari has troubles even without native player because the source isn't being loaded; will need investigation. If playback occurs before trying this, it works, but if done before playback it doesn't.

**Comment by elynema** [comment]
@Dananji Still seeing this problem on iPhone/iPad even after I thought the new Ramp build went out to avalon-dev. If I click on a section before beginning playback, the media player seems to spin and playhead doesn't advance.
