### ISSUE TITLE
[BUG] Progress bar and playhead not in sync after scrubbing + section (Android, iPhone)

### ISSUE THREAD

**Issue by abankhele** [samvera-labs/ramp#701]
**Describe the bug**
When dragging the playhead to a point beyond the sectioned segments and then selecting one of the tracks within a section, the playhead correctly moves to the selected track’s position. However, the progress bar remains stuck at the previously dragged position.

Not happening on desktop / iPhone.

**To Reproduce**
For video media player
1. Go to 'https://avalon-dev.dlib.indiana.edu/media_objects/3j3332278'
2. Drag the playhead to a time beyond the conclusion, such as 8:30.
3. Click "Play."
4. Under "Section," select "Part-II."
5. Observe: the playhead is now at the beginning of Part-II, but the progress bar remains at 8:30

 For audio player
1. Go to 'https://avalon-dev.dlib.indiana.edu/media_objects/tq57nr067'
2. Drag the playhead to a time beyond the "PART 3", such as 10:00.
3. Click "Play."
4. Under "Section," select "Part 2."
5. Observe: the playhead is now at the beginning of Part 2, but the progress bar remains at 10:00.
6. 
Note: this is also observed happening if you start playback before scrubbing, and if you click in the progress bar to scrub, rather than dragging the progress bar.

**Expected behavior**
The progress bar should synchronize with the playhead and reflect the correct duration.

**Screenshots**
If applicable, add screenshots to help explain your problem..

**Smartphone (please complete the following information):**
 - Device: Samsung Galaxy Z Fold 6 v14.0; iPhone 15 Pro
 - OS: Android, v14.0; iOS v17
 - Browser: Chrome; Safari

[Private Zenhub Video](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNnFOQnc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--4c7347ca26f407e84919b9aa437ea8b2decf9dd1/Screen%20Recording%202024-11-01%20at%2010.19.03%E2%80%AFAM.mov)

[Private Zenhub Video](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBL09OQnc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--3333cf10798eecd6111f0e9193dff28b69eb6ee1/Screen%20Recording%202024-11-01%20at%2010.54.33%E2%80%AFAM.mov)

**Additional context**

**Comment by joncameron** [comment]
Could be an issue with the structured navigation display that renders the green bar to display elapsed duration.

**Comment by elynema** [comment]
I was able to replicate this issue on iPhone today. I scrubbed in the progress bar before clicking play to near the end of the media item, then selected a section earlier.


[Private Zenhub Video](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOStqQnc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--23035bded1bf68b1867d827c1d68c551a38cbdb7/Screen%20Recording%202024-11-07%20at%2012.10.53%E2%80%AFPM.mov)

**Comment by abankhele** [comment]
Tested video and audio across all devices; everything functions as expected, with the playhead and progress bar remaining in sync throughout.
