### ISSUE TITLE
Audio player creates a vertical scroll-bar in embeds

### ISSUE THREAD

**Issue by Dananji** [samvera-labs/ramp#705]
### Description

Audio player's height is `60px` while the iframe height in Avalon embeds are set to `40px`. This creates a vertical scroll-bar in the iframe.
<img width="611" alt="Screenshot 2024-11-01 at 1 32 21 PM" src="https://github.com/user-attachments/assets/413eb553-65b2-4fa8-b96d-3ce970346f15">

### Done Looks Like
- [x] Audio player should be contained within the iframe without overflow

**Comment by elynema** [comment]
@Dananji I'm tagging this as 8.0 and moving it to Needs Refinement. Do we need to discuss potential solutions, or is it ready to work?

**Comment by Dananji** [comment]
Yes, I think we need a discussion for this.

**Comment by joncameron** [comment]
2 solutions: 
- change the iframe height and see if we can edit embeds in place with a new height value (first thing to try)
  - possible to use JS to adjust element height?  
- pull the progress bar down again, perhaps encountering zoom issues again

**Comment by elynema** [comment]
Dananji was not able to find a solution that would increase the size of the embed and also update existing embeds, so she pulled the progress bar back down inline with the other widgets like before.
