### ISSUE TITLE
[BUG] Caption icon and captions disappear when switching videos and changing quality

### ISSUE THREAD

**Issue by abankhele** [samvera-labs/ramp#717]
**Describe the bug**
When there are multiple media files, selecting a video from sections other than the first, then returning to a video with captions and changing its quality, causes the caption icon and captions to disappear.

**To Reproduce**

1. Go to 'https://avalon-dev.dlib.indiana.edu/media_objects/3j3332278'
2. Select the second media file (e.g., Venice_5.mp4).
3. Go back to the first media file (e.g., Lunchroom Manners).
4. Use the gear icon to change video quality.
5. Observe that the captions and caption icon are no longer visible.

**Expected behavior**
Changing the video quality should not impact caption visibility; the caption icon should remain visible and captions should remain visible if it is are enabled.

**Screenshots**

[Private Zenhub Video](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBN3VVQnc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--363af9571ce412ff7bfed7c1c68e9a1112101621/Screen%20Recording%202024-11-04%20at%207.24.09%E2%80%AFPM.mov)

**Desktop (please complete the following information):**
 - OS: macos
 - Browser: Chrome

**Smartphone (please complete the following information):**
 - Device: iPad Pro 12.9 2022 v16.3, iPhone 15 v17.6, Samsung Galaxy Z Fold 6 v14.0
 - OS: ios 17.6, Android, v14.0
 - Browser : chrome, safari

**Comment by elynema** [comment]
Dananji reports that this is a known issue with the quality selector plugin as part of video.js. It has not been resolved on the video.js end, but has been reported.

Second best solution is to trigger event to re-read captions in after quality change.

**Comment by Dananji** [comment]
Done looks like:
Example item to test: https://avalon-dev.dlib.indiana.edu/media_objects/g158bh28p/
- [ ] When captions are turned on, select the second section 
  -> change the quality 
  ->  observe captions icon is in the control bar with green underline 
  -> caption is selected
- [ ] When captions are turned on, select the third section 
  -> change the quality 
  -> observe captions icon is in the control bar with green underline 
  -> the first caption is selected 
  -> select the second caption option
  -> change the quality again
  -> observe second caption is still selected
- [ ] When captions are turned on, select the second section 
  -> change the quality 
  -> observe captions icon is in the control bar with green underline 
  -> the caption is selected 
  -> turn off captions 
  -> observe captions icon is in the control bar without green underline 
  -> captions off option is selected
- [ ] When captions are turned off, select the section section 
  -> change the quality 
  -> observe captions icon is in the control bar without green underline 
  -> captions off option is selected

**Comment by abankhele** [comment]
I have tested all the scenarios mentioned in the comments by Dananji, and everything is working as expected.
