### ISSUE TITLE
Default Message Text for Items Lacking placeholderCanvas property

### ISSUE THREAD

**Issue by joncameron** [samvera-labs/ramp#719]
#Description

# Done Looks Like
- [x] Double check for default message text display for restricted items without placeholderCanvas property
- [x] Add test (in not already present)

**Comment by Dananji** [comment]
This works as expected and there are relevant unit tests for this use-case.

The reason for not seeing the default message could have been manifest-specific at the time. And I was not able to reproduce this with an example empty canvas manifest from AVAnnotate anymore.
