### ISSUE TITLE
[BUG] Caption text very large on iPad full screen

### ISSUE THREAD

**Issue by elynema** [samvera-labs/ramp#727]
**Describe the bug**
When in full-screen mode in Safari on iPad, the caption text is huge.

This is not happening in full-screen on Android in Chrome, just iPad Safari.

**To Reproduce**
1. Go to https://avalon-dev.dlib.indiana.edu/media_objects/8910jt59d
2. Make sure captions are turned on
3. start playback
4. Go to full screen

**Expected behavior**
Caption text size should be smaller

**Screenshots**
<img width="544" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBd0dwQnc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--eef6183b25e5499741338202221de3d5052eee31/Screenshot%202024-11-08%20at%2012.30.25%E2%80%AFPM.png" alt="Screenshot 2024-11-08 at 12.30.25 PM.png" />

**Smartphone (please complete the following information):**
 - Device: iPad
 - OS: iOS 17
 - Browser: Safari

**Additional context**

**Comment by elynema** [comment]
Note that currently in MCO, the caption text is pretty big in full-screen on iPad:

<img width="599" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeWVwQnc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--acc49e59c4ebbb819755955b25b143a90c3ca609/screenshot-iPad%20Air%206-17.0%20%282%29.png" alt="screenshot-iPad Air 6-17.0 (2).png" />

This size actually matches most of what I'm seeing on avalon-dev. There was one version of iPad that seemed larger where I grabbed the screenshot in this issue, but I haven't been able to figure out which one.

**Comment by Dananji** [comment]
I tested this on multiple devices for Ramp in `avalon-dev` VideoJS website in Browserstack;

| Device and OS | `avalon-dev` example | `videojs.com` example |
| ------------- | ------------- | ------------- |
| iPad Pro 13 on iOS: 17.0 | ![bs_realios_Tablet_iPad Pro 13 2024-17 0 - avalon-dev](https://github.com/user-attachments/assets/a9347932-c0e9-41ba-8dac-f672ddb897be) | ![bs_realios_Tablet_iPad Pro 13 2024-17 0 - videojs](https://github.com/user-attachments/assets/72f711a4-99ad-407d-b0a9-f17ca9820449)  |
| iPad Pro 12.9 on iOS 17.0 | ![bs_realios_Tablet_iPad Pro 12 9 2021-17 0 - avalon-dev](https://github.com/user-attachments/assets/ffc7a723-e122-4e1c-8503-8e2208733f60)| ![bs_realios_Tablet_iPad Pro 12 9 2021-17 0 - videojs](https://github.com/user-attachments/assets/6caeb492-4e4b-48d1-93ba-cfae655a9e63) |
| Samsung Galaxy Tab S10 Plus on Android 14.0 | ![bs_realdroid_Tablet_Samsung Galaxy Tab S10 Plus-14 0-1752x2800 - avalon-dev](https://github.com/user-attachments/assets/e9447271-3754-4f44-b0b1-b442bd5698b6) | ![bs_realdroid_Tablet_Samsung Galaxy Tab S10 Plus-14 0-1752x2800 - videojs](https://github.com/user-attachments/assets/084bc35f-984e-4a23-83a8-1a84a06554cb) |

**Comment by joncameron** [comment]
Tested on Ramp demo site and looks good:
![Screenshot 2024-12-16 at 12 28 06 PM](https://github.com/user-attachments/assets/0cb1b035-3058-4bf9-bae0-2511d192ace7)
